In [1]:
import pandas as pd
import time
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from bs4 import BeautifulSoup

In [2]:
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))

print("Browser opened successfully")

Browser opened successfully

In [7]:
url = "https://www.cardekho.com/used-cars+in+hyderabad"
driver.get(url)
time.sleep(5)
print("page loaded successfully")

page loaded successfully

In [8]:
soup = BeautifulSoup(driver.page_source, "html.parser")

In [9]:
cards = soup.find_all("div", class_="NewUcExCard")

print('total car cards found:',len(cards))

total car cards found: 20

In [10]:
brands = ["Maruti", "Hyundai", "Honda", "Tata", "Mahindra", "Toyota",
          "Ford", "Volkswagen", "Skoda", "BMW", "Mercedes-Benz",
          "Audi", "Kia", "Renault", "Nissan", "Jeep", "MG", "BYD",
          "Land Rover","Citroen","Volvo","Mini Cooper","Jaguar","Lexus",
          "Porsche","Chevrolet","Isuzu","Datsun","Rolls-Royce","Mitsubishi",
          "Lamborghini "]

In [11]:
all_cars = []

In [12]:
for card in cards:
    try:
        #--Title--
        title = card.find("h3",class_="title").get_text(strip=True)
        
        #--year--
        year = None
        for y in range(1990,2027):
            if str(y) in title:
                year = str(y)
                title = title.replace(str(y),str(y) + " ")
                break

        #--car name--
        car_name = title.strip()

        if year:
                car_name = car_name.replace(year, "").strip()
        
        #--Brand--
        car_brand =  None
        for b in brands:
            if b in title:
                car_brand = b
                break

        #--Details--
        details = card.find("div", class_="dotsDetails")
        if details:
            parts = [x.strip() for x in details.get_text(strip=True).split("•")]
            km_driven = parts[0] if len(parts) > 0 else None
            fuel = parts[1] if len(parts) > 1 else None
            transmission = parts[2] if len(parts) > 2 else None
        else:
            km_driven = fuel = transmission = None

        #--price--
        price_tag = card.find("div", class_="priceAssured")
        price = price_tag.get_text(strip=True) if price_tag else None

        #---Append---
        all_cars.append({
            "car_brand": car_brand,
            "car_name":car_name,
            "year":year,
            "km_driven":km_driven,
            "fuel":fuel,
            "transmission":transmission,
            "price":price,
            "city":"Hyderabad"
        })

    except Exception:
        continue

In [13]:
df = pd.DataFrame(all_cars)
df.head()

,car_brand,car_name,year,km_driven,fuel,transmission,price,city
0,Renault,Renault Duster110PS Diesel RxZ,2018,"69,000kms",Diesel,Manual,₹6.90 Lakh,Hyderabad
1,Honda,Honda CityS,2013,"74,638kms",Petrol,Manual,₹3.25 Lakh,Hyderabad
2,Toyota,Toyota Innova HycrossVX 7STR Hybrid,2023,"72,000kms",Petrol,Automatic,₹24.45 Lakh,Hyderabad
3,Maruti,Maruti ErtigaSHVS ZDI,2016,"81,000kms",Diesel,Manual,₹6.85 Lakh,Hyderabad
4,BMW,BMW X3xDrive20d Expedition,2017,"90,000kms",Diesel,Automatic,₹17.50 Lakh,Hyderabad

In [14]:
all_cars = []
page = 1
max_pages = 116

while page <= max_pages:
    print(f"opening page {page}")

    if page == 1:
        url = "https://www.cardekho.com/used-cars+in+hyderabad"
    else:
        url = f"https://www.cardekho.com/used-cars+in+hyderabad/page-{page}"

    driver.get(url)
    time.sleep(5)

    soup = BeautifulSoup(driver.page_source, "html.parser")
    cards = soup.find_all("div",class_="NewUcExCard")

    print("cars found:",len(cards))

    for card in cards:
        try:
            #--Title--
            title = card.find("h3",class_="title").get_text(strip=True)

            #--year--
            year = None
            for y in range(1990, 2027):
                if str(y) in title:
                    year = str(y)
                    title = title.replace(str(y), str(y) + " ")
                    break

            #--car name--
            car_name = title.strip()

            if year:
                car_name = car_name.replace(year, "").strip()

            #--Brand--
            car_brand =  None
            for b in brands:
                if b in title:
                    car_brand = b
                    break

            #--Details--
            details = card.find("div", class_="dotsDetails")
            if details:
                parts = [x.strip() for x in details.get_text(strip=True).split("•")]
                km_driven = parts[0] if len(parts) > 0 else None
                fuel = parts[1] if len(parts) > 1 else None
                transmission = parts[2] if len(parts) > 2 else None
            else:
                km_driven = fuel = transmission = None

            #--price--
            price_tag = card.find("div", class_="priceAssured")
            price = price_tag.get_text(strip=True) if price_tag else None
            
            #---Append---
            all_cars.append({
            "car_brand": car_brand,
            "car_name":car_name,
            "year":year,
            "km_driven":km_driven,
            "fuel":fuel,
            "transmission":transmission,
            "price":price,
            "city":"Hyderabad"
            })

        except Exception:
            continue

    page += 1

opening page 1
cars found: 20
opening page 2
cars found: 20
opening page 3
cars found: 20
opening page 4
cars found: 20
opening page 5
cars found: 20
opening page 6
cars found: 20
opening page 7
cars found: 20
opening page 8
cars found: 20
opening page 9
cars found: 20
opening page 10
cars found: 28
opening page 11
cars found: 28
opening page 12
cars found: 28
opening page 13
cars found: 28
opening page 14
cars found: 28
opening page 15
cars found: 28
opening page 16
cars found: 28
opening page 17
cars found: 28
opening page 18
cars found: 20
opening page 19
cars found: 20
opening page 20
cars found: 20
opening page 21
cars found: 20
opening page 22
cars found: 20
opening page 23
cars found: 20
opening page 24
cars found: 20
opening page 25
cars found: 20
opening page 26
cars found: 20
opening page 27
cars found: 20
opening page 28
cars found: 20
opening page 29
cars found: 20
opening page 30
cars found: 20
opening page 31
cars found: 20
opening page 32
cars found: 20
opening page 33
cars found: 20
opening page 34
cars found: 20
opening page 35
cars found: 20
opening page 36
cars found: 20
opening page 37
cars found: 20
opening page 38
cars found: 20
opening page 39
cars found: 20
opening page 40
cars found: 20
opening page 41
cars found: 20
opening page 42
cars found: 20
opening page 43
cars found: 20
opening page 44
cars found: 20
opening page 45
cars found: 20
opening page 46
cars found: 20
opening page 47
cars found: 20
opening page 48
cars found: 20
opening page 49
cars found: 20
opening page 50
cars found: 20
opening page 51
cars found: 20
opening page 52
cars found: 20
opening page 53
cars found: 20
opening page 54
cars found: 20
opening page 55
cars found: 20
opening page 56
cars found: 20
opening page 57
cars found: 20
opening page 58
cars found: 20
opening page 59
cars found: 20
opening page 60
cars found: 20
opening page 61
cars found: 20
opening page 62
cars found: 20
opening page 63
cars found: 20
opening page 64
cars found: 20
opening page 65
cars found: 20
opening page 66
cars found: 20
opening page 67
cars found: 20
opening page 68
cars found: 20
opening page 69
cars found: 20
opening page 70
cars found: 20
opening page 71
cars found: 20
opening page 72
cars found: 20
opening page 73
cars found: 20
opening page 74
cars found: 20
opening page 75
cars found: 20
opening page 76
cars found: 20
opening page 77
cars found: 20
opening page 78
cars found: 20
opening page 79
cars found: 20
opening page 80
cars found: 20
opening page 81
cars found: 20
opening page 82
cars found: 20
opening page 83
cars found: 20
opening page 84
cars found: 20
opening page 85
cars found: 20
opening page 86
cars found: 20
opening page 87
cars found: 20
opening page 88
cars found: 20
opening page 89
cars found: 20
opening page 90
cars found: 20
opening page 91
cars found: 20
opening page 92
cars found: 20
opening page 93
cars found: 20
opening page 94
cars found: 20
opening page 95
cars found: 20
opening page 96
cars found: 20
opening page 97
cars found: 20
opening page 98
cars found: 20
opening page 99
cars found: 20
opening page 100
cars found: 20
opening page 101
cars found: 20
opening page 102
cars found: 20
opening page 103
cars found: 20
opening page 104
cars found: 20
opening page 105
cars found: 20
opening page 106
cars found: 20
opening page 107
cars found: 20
opening page 108
cars found: 20
opening page 109
cars found: 20
opening page 110
cars found: 20
opening page 111
cars found: 20
opening page 112
cars found: 20
opening page 113
cars found: 20
opening page 114
cars found: 20
opening page 115
cars found: 20
opening page 116
cars found: 20

In [15]:
df = pd.DataFrame(all_cars)
print("Total rows collected:", len(df))
df.head()

Total rows collected: 2384

,car_brand,car_name,year,km_driven,fuel,transmission,price,city
0,Audi,Audi A4Technology,2021,"30,000kms",Petrol,Automatic,₹35 Lakh,Hyderabad
1,Honda,Honda CityS,2013,"74,638kms",Petrol,Manual,₹3.25 Lakh,Hyderabad
2,Toyota,Toyota Innova HycrossVX 7STR Hybrid,2023,"72,000kms",Petrol,Automatic,₹24.45 Lakh,Hyderabad
3,Maruti,Maruti ErtigaSHVS ZDI,2016,"81,000kms",Diesel,Manual,₹6.85 Lakh,Hyderabad
4,Tata,Tata NexonPure Diesel,2024,"22,000kms",Diesel,Manual,₹10.50 Lakh,Hyderabad

In [16]:
df.to_csv(r'C:\Users\admin\Desktop\Used_Cars_ Price_Analysis\data\raw\used_cars_hyderabad_raw.csv')
print('csv saved:used_cars_hyderabad_raw.csv')

csv saved:used_cars_hyderabad_raw.csv

# BANGALORE

In [17]:
all_cars = []
page = 1
max_pages = 204

while page <= max_pages:
    print(f"opening page {page}")

    if page == 1:
        url = "https://www.cardekho.com/used-cars+in+bangalore"
    else:
        url = f"https://www.cardekho.com/used-cars+in+bangalore/page-{page}"

    driver.get(url)
    time.sleep(5)

    soup = BeautifulSoup(driver.page_source, "html.parser")
    cards = soup.find_all("div",class_="NewUcExCard")

    print("cars found:",len(cards))

    for card in cards:
        try:
            #--Title--
            title = card.find("h3",class_="title").get_text(strip=True)

             

            #--year--
            year = None
            for y in range(1990, 2027):
                if str(y) in title:
                    year = str(y)
                    title = title.replace(str(y), str(y) + " ")
                    break
                    
            #--car name--
            car_name = title.strip()
            if year:
                car_name = car_name.replace(year, "").strip()

            #--Brand--
            car_brand =  None
            for b in brands:
                if b in title:
                    car_brand = b
                    break

            #--Details--
            details = card.find("div", class_="dotsDetails")
            if details:
                parts = [x.strip() for x in details.get_text(strip=True).split("•")]
                km_driven = parts[0] if len(parts) > 0 else None
                fuel = parts[1] if len(parts) > 1 else None
                transmission = parts[2] if len(parts) > 2 else None
            else:
                km_driven = fuel = transmission = None

            #--price--
            price_tag = card.find("div", class_="priceAssured")
            price = price_tag.get_text(strip=True) if price_tag else None
            
            #---Append---
            all_cars.append({
            "car_brand": car_brand,
            "car_name":car_name,
            "year":year,
            "km_driven":km_driven,
            "fuel":fuel,
            "transmission":transmission,
            "price":price,
            "city":"bangalore"
            })

        except Exception:
            continue

    page += 1

opening page 1
cars found: 20
opening page 2
cars found: 20
opening page 3
cars found: 20
opening page 4
cars found: 20
opening page 5
cars found: 20
opening page 6
cars found: 20
opening page 7
cars found: 20
opening page 8
cars found: 20
opening page 9
cars found: 20
opening page 10
cars found: 20
opening page 11
cars found: 20
opening page 12
cars found: 20
opening page 13
cars found: 20
opening page 14
cars found: 20
opening page 15
cars found: 20
opening page 16
cars found: 20
opening page 17
cars found: 20
opening page 18
cars found: 20
opening page 19
cars found: 20
opening page 20
cars found: 20
opening page 21
cars found: 20
opening page 22
cars found: 20
opening page 23
cars found: 20
opening page 24
cars found: 20
opening page 25
cars found: 20
opening page 26
cars found: 20
opening page 27
cars found: 20
opening page 28
cars found: 20
opening page 29
cars found: 20
opening page 30
cars found: 20
opening page 31
cars found: 20
opening page 32
cars found: 20
opening page 33
cars found: 20
opening page 34
cars found: 20
opening page 35
cars found: 20
opening page 36
cars found: 20
opening page 37
cars found: 20
opening page 38
cars found: 20
opening page 39
cars found: 20
opening page 40
cars found: 20
opening page 41
cars found: 20
opening page 42
cars found: 20
opening page 43
cars found: 20
opening page 44
cars found: 20
opening page 45
cars found: 20
opening page 46
cars found: 20
opening page 47
cars found: 20
opening page 48
cars found: 20
opening page 49
cars found: 20
opening page 50
cars found: 20
opening page 51
cars found: 20
opening page 52
cars found: 20
opening page 53
cars found: 20
opening page 54
cars found: 20
opening page 55
cars found: 20
opening page 56
cars found: 20
opening page 57
cars found: 20
opening page 58
cars found: 20
opening page 59
cars found: 20
opening page 60
cars found: 20
opening page 61
cars found: 20
opening page 62
cars found: 20
opening page 63
cars found: 20
opening page 64
cars found: 20
opening page 65
cars found: 20
opening page 66
cars found: 20
opening page 67
cars found: 20
opening page 68
cars found: 20
opening page 69
cars found: 20
opening page 70
cars found: 20
opening page 71
cars found: 20
opening page 72
cars found: 20
opening page 73
cars found: 20
opening page 74
cars found: 20
opening page 75
cars found: 20
opening page 76
cars found: 20
opening page 77
cars found: 20
opening page 78
cars found: 20
opening page 79
cars found: 20
opening page 80
cars found: 20
opening page 81
cars found: 20
opening page 82
cars found: 20
opening page 83
cars found: 20
opening page 84
cars found: 20
opening page 85
cars found: 20
opening page 86
cars found: 20
opening page 87
cars found: 20
opening page 88
cars found: 20
opening page 89
cars found: 20
opening page 90
cars found: 20
opening page 91
cars found: 20
opening page 92
cars found: 20
opening page 93
cars found: 20
opening page 94
cars found: 20
opening page 95
cars found: 20
opening page 96
cars found: 20
opening page 97
cars found: 20
opening page 98
cars found: 20
opening page 99
cars found: 20
opening page 100
cars found: 20
opening page 101
cars found: 20
opening page 102
cars found: 20
opening page 103
cars found: 20
opening page 104
cars found: 20
opening page 105
cars found: 20
opening page 106
cars found: 20
opening page 107
cars found: 20
opening page 108
cars found: 20
opening page 109
cars found: 20
opening page 110
cars found: 20
opening page 111
cars found: 20
opening page 112
cars found: 20
opening page 113
cars found: 20
opening page 114
cars found: 20
opening page 115
cars found: 20
opening page 116
cars found: 20
opening page 117
cars found: 20
opening page 118
cars found: 20
opening page 119
cars found: 20
opening page 120
cars found: 20
opening page 121
cars found: 20
opening page 122
cars found: 20
opening page 123
cars found: 20
opening page 124
cars found: 20
opening page 125
cars found: 20
opening page 126
cars found: 20
opening page 127
cars found: 20
opening page 128
cars found: 20
opening page 129
cars found: 20
opening page 130
cars found: 20
opening page 131
cars found: 20
opening page 132
cars found: 20
opening page 133
cars found: 20
opening page 134
cars found: 20
opening page 135
cars found: 20
opening page 136
cars found: 20
opening page 137
cars found: 20
opening page 138
cars found: 20
opening page 139
cars found: 20
opening page 140
cars found: 20
opening page 141
cars found: 20
opening page 142
cars found: 20
opening page 143
cars found: 20
opening page 144
cars found: 20
opening page 145
cars found: 20
opening page 146
cars found: 20
opening page 147
cars found: 20
opening page 148
cars found: 20
opening page 149
cars found: 20
opening page 150
cars found: 20
opening page 151
cars found: 20
opening page 152
cars found: 20
opening page 153
cars found: 20
opening page 154
cars found: 20
opening page 155
cars found: 20
opening page 156
cars found: 20
opening page 157
cars found: 20
opening page 158
cars found: 20
opening page 159
cars found: 20
opening page 160
cars found: 20
opening page 161
cars found: 20
opening page 162
cars found: 20
opening page 163
cars found: 20
opening page 164
cars found: 20
opening page 165
cars found: 20
opening page 166
cars found: 20
opening page 167
cars found: 20
opening page 168
cars found: 20
opening page 169
cars found: 20
opening page 170
cars found: 20
opening page 171
cars found: 20
opening page 172
cars found: 20
opening page 173
cars found: 20
opening page 174
cars found: 20
opening page 175
cars found: 20
opening page 176
cars found: 20
opening page 177
cars found: 20
opening page 178
cars found: 20
opening page 179
cars found: 20
opening page 180
cars found: 20
opening page 181
cars found: 20
opening page 182
cars found: 20
opening page 183
cars found: 20
opening page 184
cars found: 20
opening page 185
cars found: 20
opening page 186
cars found: 20
opening page 187
cars found: 20
opening page 188
cars found: 20
opening page 189
cars found: 20
opening page 190
cars found: 20
opening page 191
cars found: 20
opening page 192
cars found: 20
opening page 193
cars found: 20
opening page 194
cars found: 20
opening page 195
cars found: 20
opening page 196
cars found: 20
opening page 197
cars found: 20
opening page 198
cars found: 20
opening page 199
cars found: 20
opening page 200
cars found: 20
opening page 201
cars found: 20
opening page 202
cars found: 20
opening page 203
cars found: 20
opening page 204
cars found: 20

In [18]:
df_bangalore = pd.DataFrame(all_cars)
print("Total Bangalore cars:", len(df_bangalore))
df_bangalore.head()

Total Bangalore cars: 4080

,car_brand,car_name,year,km_driven,fuel,transmission,price,city
0,Mercedes-Benz,Mercedes-Benz GLE300d BSVI,2022,"27,976kms",Diesel,Automatic,₹67.75 Lakh,bangalore
1,Renault,Renault KWIDRXL,2021,"29,042kms",Petrol,Manual,₹3.70 Lakh,bangalore
2,Maruti,Maruti IgnisSigma BSVI,2022,"46,564kms",Petrol,Manual,₹4.52 Lakh,bangalore
3,Hyundai,Hyundai Verna1.6 VTVT AT SX,2016,"95,846kms",Petrol,Automatic,₹5.93 Lakh,bangalore
4,Kia,Kia SeltosGTX Plus Diesel AT,2023,"24,860kms",Diesel,Automatic,₹19.49 Lakh,bangalore

In [19]:
df_bangalore.to_csv(r"C:\Users\admin\Desktop\Used_Cars_ Price_Analysis\data\raw\used_cars_bangalore_raw.csv", index=False)
print("Saved: used_cars_bangalore_raw.csv")

Saved: used_cars_bangalore_raw.csv

# CHENNAI

In [20]:
all_cars = []
page = 1
max_pages = 67

while page <= max_pages:
    print(f"opening page {page}")

    if page == 1:
        url = "https://www.cardekho.com/used-cars+in+chennai"
    else:
        url = f"https://www.cardekho.com/used-cars+in+chennai/page-{page}"

    driver.get(url)
    time.sleep(5)

    soup = BeautifulSoup(driver.page_source, "html.parser")
    cards = soup.find_all("div",class_="NewUcExCard")

    print("cars found:",len(cards))

    for card in cards:
        try:
            #--Title--
            title = card.find("h3",class_="title").get_text(strip=True)

             

            #--year--
            year = None
            for y in range(1990, 2027):
                if str(y) in title:
                    year = str(y)
                    title = title.replace(str(y), str(y) + " ")

                    break
                    
            #--car name--
            car_name = title.strip()
            if year:
                car_name = car_name.replace(year, "").strip()

            #--Brand--
            car_brand =  None
            for b in brands:
                if b in title:
                    car_brand = b
                    break

            #--Details--
            details = card.find("div", class_="dotsDetails")
            if details:
                parts = [x.strip() for x in details.get_text(strip=True).split("•")]
                km_driven = parts[0] if len(parts) > 0 else None
                fuel = parts[1] if len(parts) > 1 else None
                transmission = parts[2] if len(parts) > 2 else None
            else:
                km_driven = fuel = transmission = None


            #--price--
            price_tag = card.find("div", class_="priceAssured")
            price = price_tag.get_text(strip=True) if price_tag else None
            
            #---Append---
            all_cars.append({
            "car_brand": car_brand,
            "car_name":car_name,
            "year":year,
            "km_driven":km_driven,
            "fuel":fuel,
            "transmission":transmission,
            "price":price,
            "city":"chennai"
            })

        except Exception:
            continue

    page += 1

opening page 1
cars found: 20
opening page 2
cars found: 20
opening page 3
cars found: 20
opening page 4
cars found: 20
opening page 5
cars found: 20
opening page 6
cars found: 20
opening page 7
cars found: 20
opening page 8
cars found: 20
opening page 9
cars found: 20
opening page 10
cars found: 20
opening page 11
cars found: 20
opening page 12
cars found: 20
opening page 13
cars found: 20
opening page 14
cars found: 20
opening page 15
cars found: 20
opening page 16
cars found: 20
opening page 17
cars found: 20
opening page 18
cars found: 20
opening page 19
cars found: 20
opening page 20
cars found: 20
opening page 21
cars found: 20
opening page 22
cars found: 20
opening page 23
cars found: 20
opening page 24
cars found: 20
opening page 25
cars found: 20
opening page 26
cars found: 20
opening page 27
cars found: 20
opening page 28
cars found: 20
opening page 29
cars found: 20
opening page 30
cars found: 20
opening page 31
cars found: 20
opening page 32
cars found: 20
opening page 33
cars found: 20
opening page 34
cars found: 20
opening page 35
cars found: 20
opening page 36
cars found: 20
opening page 37
cars found: 20
opening page 38
cars found: 20
opening page 39
cars found: 20
opening page 40
cars found: 20
opening page 41
cars found: 20
opening page 42
cars found: 20
opening page 43
cars found: 20
opening page 44
cars found: 20
opening page 45
cars found: 20
opening page 46
cars found: 20
opening page 47
cars found: 20
opening page 48
cars found: 20
opening page 49
cars found: 20
opening page 50
cars found: 20
opening page 51
cars found: 20
opening page 52
cars found: 20
opening page 53
cars found: 20
opening page 54
cars found: 20
opening page 55
cars found: 20
opening page 56
cars found: 20
opening page 57
cars found: 20
opening page 58
cars found: 20
opening page 59
cars found: 20
opening page 60
cars found: 20
opening page 61
cars found: 20
opening page 62
cars found: 20
opening page 63
cars found: 20
opening page 64
cars found: 20
opening page 65
cars found: 20
opening page 66
cars found: 20
opening page 67
cars found: 20

In [21]:
df_chennai = pd.DataFrame(all_cars)
print("Total chennai cars:", len(df_chennai))
df_chennai.head()

Total chennai cars: 1340

,car_brand,car_name,year,km_driven,fuel,transmission,price,city
0,Kia,Kia CarensLuxury Plus Diesel AT BSVI,2022,"31,000kms",Diesel,Automatic,₹15.50 Lakh,chennai
1,Renault,Renault KigerRXT AMT Opt DT,2022,"29,013kms",Petrol,Automatic,₹6.21 Lakh,chennai
2,Kia,Kia SeltosHTK Plus Diesel iMT,2023,"47,665kms",Diesel,Automatic,₹10.03 Lakh,chennai
3,Mercedes-Benz,Mercedes-Benz S-ClassS 350 d,2014,"74,000kms",Diesel,Automatic,₹36 Lakh,chennai
4,Honda,Honda ElevateV Non RF,2023,"40,617kms",Petrol,Manual,₹10.25 Lakh,chennai

In [22]:
df_chennai.to_csv(r"C:\Users\admin\Desktop\Used_Cars_ Price_Analysis\data\raw\used_cars_chennai_raw.csv", index=False)
print("Saved: used_cars_chennai_raw.csv")

Saved: used_cars_chennai_raw.csv

# MUMBAI

In [23]:
all_cars = []
page = 1
max_pages = 206

while page <= max_pages:
    print(f"opening page {page}")

    if page == 1:
        url = "https://www.cardekho.com/used-cars+in+mumbai"
    else:
        url = f"https://www.cardekho.com/used-cars+in+mumbai/page-{page}"

    driver.get(url)
    time.sleep(5)

    soup = BeautifulSoup(driver.page_source, "html.parser")
    cards = soup.find_all("div",class_="NewUcExCard")

    print("cars found:",len(cards))

    for card in cards:
        try:
            #--Title--
            title = card.find("h3",class_="title").get_text(strip=True)

            

            #--year--
            year = None
            for y in range(1990, 2027):
                if str(y) in title:
                    year = str(y)
                    title = title.replace(str(y), str(y) + " ")

                    break

            #--car name--
            car_name = title.strip()
            if year:
                car_name = car_name.replace(year, "").strip()

            #--Brand--
            car_brand =  None
            for b in brands:
                if b in title:
                    car_brand = b
                    break

            #--Details--
            details = card.find("div", class_="dotsDetails")
            if details:
                parts = [x.strip() for x in details.get_text(strip=True).split("•")]
                km_driven = parts[0] if len(parts) > 0 else None
                fuel = parts[1] if len(parts) > 1 else None
                transmission = parts[2] if len(parts) > 2 else None
            else:
                km_driven = fuel = transmission = None


            #--price--
            price_tag = card.find("div", class_="priceAssured")
            price = price_tag.get_text(strip=True) if price_tag else None
            
            #---Append---
            all_cars.append({
            "car_brand": car_brand,
            "car_name":car_name,
            "year":year,
            "km_driven":km_driven,
            "fuel":fuel,
            "transmission":transmission,
            "price":price,
            "city":"mumbai"
            })

        except Exception:
            continue

    page += 1

opening page 1
cars found: 20
opening page 2
cars found: 20
opening page 3
cars found: 20
opening page 4
cars found: 20
opening page 5
cars found: 20
opening page 6
cars found: 20
opening page 7
cars found: 20
opening page 8
cars found: 20
opening page 9
cars found: 20
opening page 10
cars found: 20
opening page 11
cars found: 20
opening page 12
cars found: 20
opening page 13
cars found: 20
opening page 14
cars found: 20
opening page 15
cars found: 20
opening page 16
cars found: 20
opening page 17
cars found: 20
opening page 18
cars found: 20
opening page 19
cars found: 20
opening page 20
cars found: 20
opening page 21
cars found: 20
opening page 22
cars found: 20
opening page 23
cars found: 20
opening page 24
cars found: 20
opening page 25
cars found: 20
opening page 26
cars found: 20
opening page 27
cars found: 20
opening page 28
cars found: 20
opening page 29
cars found: 20
opening page 30
cars found: 20
opening page 31
cars found: 20
opening page 32
cars found: 20
opening page 33
cars found: 20
opening page 34
cars found: 20
opening page 35
cars found: 20
opening page 36
cars found: 20
opening page 37
cars found: 20
opening page 38
cars found: 20
opening page 39
cars found: 20
opening page 40
cars found: 20
opening page 41
cars found: 20
opening page 42
cars found: 20
opening page 43
cars found: 20
opening page 44
cars found: 20
opening page 45
cars found: 20
opening page 46
cars found: 20
opening page 47
cars found: 20
opening page 48
cars found: 20
opening page 49
cars found: 20
opening page 50
cars found: 20
opening page 51
cars found: 20
opening page 52
cars found: 20
opening page 53
cars found: 20
opening page 54
cars found: 20
opening page 55
cars found: 20
opening page 56
cars found: 20
opening page 57
cars found: 20
opening page 58
cars found: 20
opening page 59
cars found: 20
opening page 60
cars found: 20
opening page 61
cars found: 20
opening page 62
cars found: 20
opening page 63
cars found: 20
opening page 64
cars found: 20
opening page 65
cars found: 20
opening page 66
cars found: 20
opening page 67
cars found: 20
opening page 68
cars found: 20
opening page 69
cars found: 20
opening page 70
cars found: 20
opening page 71
cars found: 20
opening page 72
cars found: 20
opening page 73
cars found: 20
opening page 74
cars found: 20
opening page 75
cars found: 20
opening page 76
cars found: 20
opening page 77
cars found: 20
opening page 78
cars found: 20
opening page 79
cars found: 20
opening page 80
cars found: 20
opening page 81
cars found: 20
opening page 82
cars found: 20
opening page 83
cars found: 20
opening page 84
cars found: 20
opening page 85
cars found: 20
opening page 86
cars found: 20
opening page 87
cars found: 20
opening page 88
cars found: 20
opening page 89
cars found: 20
opening page 90
cars found: 20
opening page 91
cars found: 20
opening page 92
cars found: 20
opening page 93
cars found: 20
opening page 94
cars found: 20
opening page 95
cars found: 20
opening page 96
cars found: 20
opening page 97
cars found: 20
opening page 98
cars found: 20
opening page 99
cars found: 20
opening page 100
cars found: 20
opening page 101
cars found: 20
opening page 102
cars found: 20
opening page 103
cars found: 20
opening page 104
cars found: 20
opening page 105
cars found: 20
opening page 106
cars found: 20
opening page 107
cars found: 20
opening page 108
cars found: 20
opening page 109
cars found: 20
opening page 110
cars found: 20
opening page 111
cars found: 20
opening page 112
cars found: 20
opening page 113
cars found: 20
opening page 114
cars found: 20
opening page 115
cars found: 20
opening page 116
cars found: 20
opening page 117
cars found: 20
opening page 118
cars found: 20
opening page 119
cars found: 20
opening page 120
cars found: 20
opening page 121
cars found: 20
opening page 122
cars found: 20
opening page 123
cars found: 20
opening page 124
cars found: 20
opening page 125
cars found: 20
opening page 126
cars found: 20
opening page 127
cars found: 20
opening page 128
cars found: 20
opening page 129
cars found: 20
opening page 130
cars found: 20
opening page 131
cars found: 20
opening page 132
cars found: 20
opening page 133
cars found: 20
opening page 134
cars found: 20
opening page 135
cars found: 20
opening page 136
cars found: 20
opening page 137
cars found: 20
opening page 138
cars found: 20
opening page 139
cars found: 20
opening page 140
cars found: 20
opening page 141
cars found: 20
opening page 142
cars found: 20
opening page 143
cars found: 20
opening page 144
cars found: 20
opening page 145
cars found: 20
opening page 146
cars found: 20
opening page 147
cars found: 20
opening page 148
cars found: 20
opening page 149
cars found: 20
opening page 150
cars found: 20
opening page 151
cars found: 20
opening page 152
cars found: 20
opening page 153
cars found: 20
opening page 154
cars found: 20
opening page 155
cars found: 20
opening page 156
cars found: 20
opening page 157
cars found: 20
opening page 158
cars found: 20
opening page 159
cars found: 20
opening page 160
cars found: 20
opening page 161
cars found: 20
opening page 162
cars found: 20
opening page 163
cars found: 20
opening page 164
cars found: 20
opening page 165
cars found: 20
opening page 166
cars found: 20
opening page 167
cars found: 20
opening page 168
cars found: 20
opening page 169
cars found: 20
opening page 170
cars found: 20
opening page 171
cars found: 20
opening page 172
cars found: 20
opening page 173
cars found: 20
opening page 174
cars found: 20
opening page 175
cars found: 20
opening page 176
cars found: 20
opening page 177
cars found: 20
opening page 178
cars found: 20
opening page 179
cars found: 20
opening page 180
cars found: 20
opening page 181
cars found: 20
opening page 182
cars found: 20
opening page 183
cars found: 20
opening page 184
cars found: 20
opening page 185
cars found: 20
opening page 186
cars found: 20
opening page 187
cars found: 20
opening page 188
cars found: 20
opening page 189
cars found: 20
opening page 190
cars found: 20
opening page 191
cars found: 20
opening page 192
cars found: 20
opening page 193
cars found: 20
opening page 194
cars found: 20
opening page 195
cars found: 20
opening page 196
cars found: 20
opening page 197
cars found: 20
opening page 198
cars found: 20
opening page 199
cars found: 20
opening page 200
cars found: 20
opening page 201
cars found: 20
opening page 202
cars found: 20
opening page 203
cars found: 20
opening page 204
cars found: 20
opening page 205
cars found: 20
opening page 206
cars found: 20

In [24]:
df_mumbai = pd.DataFrame(all_cars)
print("Total mumbai cars:", len(df_mumbai))
df_mumbai.head()

Total mumbai cars: 4120

,car_brand,car_name,year,km_driven,fuel,transmission,price,city
0,Jeep,Jeep Compass1.4 Longitude Plus AT,2018,"55,000kms",Petrol,Automatic,₹7.49 Lakh,mumbai
1,Kia,Kia SeltosGTX Plus S Turbo DCT,2023,"49,718kms",Petrol,Automatic,₹16.25 Lakh,mumbai
2,Hyundai,Hyundai CretaSX Opt Knight IVT,2023,"30,374kms",Petrol,Automatic,₹15.25 Lakh,mumbai
3,Mercedes-Benz,Mercedes-Benz E-ClassE250 CDI Avantgarde,2016,"53,000kms",Diesel,Automatic,₹15.90 Lakh,mumbai
4,MG,MG GlosterSavvy 4x2 7Str,2024,"10,000kms",Diesel,Automatic,₹38 Lakh,mumbai

In [25]:
df_mumbai.to_csv(r"C:\Users\admin\Desktop\Used_Cars_ Price_Analysis\data\raw\used_cars_mumbai_raw.csv", index=False)
print("Saved: used_cars_mumbai_raw.csv")

Saved: used_cars_mumbai_raw.csv

# DELHI - NCR

In [26]:
all_cars = []
page = 1
max_pages = 493

while page <= max_pages:
    print(f"opening page {page}")

    if page == 1:
        url = "https://www.cardekho.com/used-cars+in+delhi-ncr"
    else:
        url = f"https://www.cardekho.com/used-cars+in+delhi-ncr/page-{page}"

    driver.get(url)
    time.sleep(5)

    soup = BeautifulSoup(driver.page_source, "html.parser")
    cards = soup.find_all("div",class_="NewUcExCard")

    print("cars found:",len(cards))

    for card in cards:
        try:
            #--Title--
            title = card.find("h3",class_="title").get_text(strip=True)

            

            #--year--
            year = None
            for y in range(1990, 2027):
                if str(y) in title:
                    year = str(y)
                    title = title.replace(str(y), str(y) + " ")

                    break

            #--car name--
            car_name = title.strip()
            if year:
                car_name = car_name.replace(year, "").strip()

            #--Brand--
            car_brand =  None
            for b in brands:
                if b in title:
                    car_brand = b
                    break

            #--Details--
            details = card.find("div", class_="dotsDetails")
            if details:
                parts = [x.strip() for x in details.get_text(strip=True).split("•")]
                km_driven = parts[0] if len(parts) > 0 else None
                fuel = parts[1] if len(parts) > 1 else None
                transmission = parts[2] if len(parts) > 2 else None
            else:
                km_driven = fuel = transmission = None


            #--price--
            price_tag = card.find("div", class_="priceAssured")
            price = price_tag.get_text(strip=True) if price_tag else None
            
            #---Append---
            all_cars.append({
            "car_brand": car_brand,
            "car_name":car_name,
            "year":year,
            "km_driven":km_driven,
            "fuel":fuel,
            "transmission":transmission,
            "price":price,
            "city":"delhi-ncr"
            })

        except Exception:
            continue

    page += 1

opening page 1
cars found: 20
opening page 2
cars found: 20
opening page 3
cars found: 20
opening page 4
cars found: 20
opening page 5
cars found: 20
opening page 6
cars found: 20
opening page 7
cars found: 20
opening page 8
cars found: 20
opening page 9
cars found: 20
opening page 10
cars found: 20
opening page 11
cars found: 20
opening page 12
cars found: 20
opening page 13
cars found: 20
opening page 14
cars found: 20
opening page 15
cars found: 20
opening page 16
cars found: 20
opening page 17
cars found: 20
opening page 18
cars found: 20
opening page 19
cars found: 20
opening page 20
cars found: 20
opening page 21
cars found: 20
opening page 22
cars found: 20
opening page 23
cars found: 20
opening page 24
cars found: 20
opening page 25
cars found: 20
opening page 26
cars found: 20
opening page 27
cars found: 20
opening page 28
cars found: 20
opening page 29
cars found: 20
opening page 30
cars found: 20
opening page 31
cars found: 20
opening page 32
cars found: 20
opening page 33
cars found: 20
opening page 34
cars found: 20
opening page 35
cars found: 20
opening page 36
cars found: 20
opening page 37
cars found: 20
opening page 38
cars found: 20
opening page 39
cars found: 20
opening page 40
cars found: 20
opening page 41
cars found: 20
opening page 42
cars found: 20
opening page 43
cars found: 20
opening page 44
cars found: 20
opening page 45
cars found: 20
opening page 46
cars found: 20
opening page 47
cars found: 20
opening page 48
cars found: 20
opening page 49
cars found: 20
opening page 50
cars found: 20
opening page 51
cars found: 20
opening page 52
cars found: 20
opening page 53
cars found: 20
opening page 54
cars found: 20
opening page 55
cars found: 20
opening page 56
cars found: 20
opening page 57
cars found: 20
opening page 58
cars found: 20
opening page 59
cars found: 20
opening page 60
cars found: 20
opening page 61
cars found: 20
opening page 62
cars found: 20
opening page 63
cars found: 20
opening page 64
cars found: 20
opening page 65
cars found: 20
opening page 66
cars found: 20
opening page 67
cars found: 20
opening page 68
cars found: 20
opening page 69
cars found: 20
opening page 70
cars found: 20
opening page 71
cars found: 20
opening page 72
cars found: 20
opening page 73
cars found: 20
opening page 74
cars found: 20
opening page 75
cars found: 20
opening page 76
cars found: 20
opening page 77
cars found: 20
opening page 78
cars found: 20
opening page 79
cars found: 20
opening page 80
cars found: 20
opening page 81
cars found: 20
opening page 82
cars found: 20
opening page 83
cars found: 20
opening page 84
cars found: 20
opening page 85
cars found: 20
opening page 86
cars found: 20
opening page 87
cars found: 20
opening page 88
cars found: 20
opening page 89
cars found: 20
opening page 90
cars found: 20
opening page 91
cars found: 20
opening page 92
cars found: 20
opening page 93
cars found: 20
opening page 94
cars found: 20
opening page 95
cars found: 20
opening page 96
cars found: 20
opening page 97
cars found: 20
opening page 98
cars found: 20
opening page 99
cars found: 20
opening page 100
cars found: 20
opening page 101
cars found: 20
opening page 102
cars found: 20
opening page 103
cars found: 20
opening page 104
cars found: 20
opening page 105
cars found: 20
opening page 106
cars found: 20
opening page 107
cars found: 20
opening page 108
cars found: 20
opening page 109
cars found: 20
opening page 110
cars found: 20
opening page 111
cars found: 20
opening page 112
cars found: 20
opening page 113
cars found: 20
opening page 114
cars found: 20
opening page 115
cars found: 20
opening page 116
cars found: 20
opening page 117
cars found: 20
opening page 118
cars found: 20
opening page 119
cars found: 20
opening page 120
cars found: 20
opening page 121
cars found: 20
opening page 122
cars found: 20
opening page 123
cars found: 20
opening page 124
cars found: 20
opening page 125
cars found: 20
opening page 126
cars found: 20
opening page 127
cars found: 20
opening page 128
cars found: 20
opening page 129
cars found: 20
opening page 130
cars found: 20
opening page 131
cars found: 20
opening page 132
cars found: 20
opening page 133
cars found: 20
opening page 134
cars found: 20
opening page 135
cars found: 20
opening page 136
cars found: 20
opening page 137
cars found: 20
opening page 138
cars found: 20
opening page 139
cars found: 20
opening page 140
cars found: 20
opening page 141
cars found: 20
opening page 142
cars found: 20
opening page 143
cars found: 20
opening page 144
cars found: 20
opening page 145
cars found: 20
opening page 146
cars found: 20
opening page 147
cars found: 20
opening page 148
cars found: 20
opening page 149
cars found: 20
opening page 150
cars found: 20
opening page 151
cars found: 20
opening page 152
cars found: 20
opening page 153
cars found: 20
opening page 154
cars found: 20
opening page 155
cars found: 20
opening page 156
cars found: 20
opening page 157
cars found: 20
opening page 158
cars found: 20
opening page 159
cars found: 20
opening page 160
cars found: 20
opening page 161
cars found: 20
opening page 162
cars found: 20
opening page 163
cars found: 20
opening page 164
cars found: 20
opening page 165
cars found: 20
opening page 166
cars found: 20
opening page 167
cars found: 20
opening page 168
cars found: 20
opening page 169
cars found: 20
opening page 170
cars found: 20
opening page 171
cars found: 20
opening page 172
cars found: 20
opening page 173
cars found: 20
opening page 174
cars found: 20
opening page 175
cars found: 20
opening page 176
cars found: 20
opening page 177
cars found: 20
opening page 178
cars found: 20
opening page 179
cars found: 20
opening page 180
cars found: 20
opening page 181
cars found: 20
opening page 182
cars found: 20
opening page 183
cars found: 20
opening page 184
cars found: 20
opening page 185
cars found: 20
opening page 186
cars found: 20
opening page 187
cars found: 20
opening page 188
cars found: 20
opening page 189
cars found: 20
opening page 190
cars found: 20
opening page 191
cars found: 20
opening page 192
cars found: 20
opening page 193
cars found: 20
opening page 194
cars found: 20
opening page 195
cars found: 20
opening page 196
cars found: 20
opening page 197
cars found: 20
opening page 198
cars found: 20
opening page 199
cars found: 20
opening page 200
cars found: 20
opening page 201
cars found: 20
opening page 202
cars found: 20
opening page 203
cars found: 20
opening page 204
cars found: 20
opening page 205
cars found: 20
opening page 206
cars found: 20
opening page 207
cars found: 20
opening page 208
cars found: 20
opening page 209
cars found: 20
opening page 210
cars found: 20
opening page 211
cars found: 20
opening page 212
cars found: 20
opening page 213
cars found: 20
opening page 214
cars found: 20
opening page 215
cars found: 20
opening page 216
cars found: 20
opening page 217
cars found: 20
opening page 218
cars found: 20
opening page 219
cars found: 20
opening page 220
cars found: 20
opening page 221
cars found: 20
opening page 222
cars found: 20
opening page 223
cars found: 20
opening page 224
cars found: 20
opening page 225
cars found: 20
opening page 226
cars found: 20
opening page 227
cars found: 20
opening page 228
cars found: 20
opening page 229
cars found: 20
opening page 230
cars found: 20
opening page 231
cars found: 20
opening page 232
cars found: 20
opening page 233
cars found: 20
opening page 234
cars found: 20
opening page 235
cars found: 20
opening page 236
cars found: 20
opening page 237
cars found: 20
opening page 238
cars found: 20
opening page 239
cars found: 20
opening page 240
cars found: 20
opening page 241
cars found: 20
opening page 242
cars found: 20
opening page 243
cars found: 20
opening page 244
cars found: 20
opening page 245
cars found: 20
opening page 246
cars found: 20
opening page 247
cars found: 20
opening page 248
cars found: 20
opening page 249
cars found: 20
opening page 250
cars found: 20
opening page 251
cars found: 20
opening page 252
cars found: 20
opening page 253
cars found: 20
opening page 254
cars found: 20
opening page 255
cars found: 20
opening page 256
cars found: 20
opening page 257
cars found: 20
opening page 258
cars found: 20
opening page 259
cars found: 20
opening page 260
cars found: 20
opening page 261
cars found: 20
opening page 262
cars found: 20
opening page 263
cars found: 20
opening page 264
cars found: 20
opening page 265
cars found: 20
opening page 266
cars found: 20
opening page 267
cars found: 20
opening page 268
cars found: 20
opening page 269
cars found: 20
opening page 270
cars found: 20
opening page 271
cars found: 20
opening page 272
cars found: 20
opening page 273
cars found: 20
opening page 274
cars found: 20
opening page 275
cars found: 20
opening page 276
cars found: 20
opening page 277
cars found: 20
opening page 278
cars found: 20
opening page 279
cars found: 20
opening page 280
cars found: 20
opening page 281
cars found: 20
opening page 282
cars found: 20
opening page 283
cars found: 20
opening page 284
cars found: 20
opening page 285
cars found: 20
opening page 286
cars found: 20
opening page 287
cars found: 20
opening page 288
cars found: 20
opening page 289
cars found: 20
opening page 290
cars found: 20
opening page 291
cars found: 20
opening page 292
cars found: 20
opening page 293
cars found: 20
opening page 294
cars found: 20
opening page 295
cars found: 20
opening page 296
cars found: 20
opening page 297
cars found: 20
opening page 298
cars found: 20
opening page 299
cars found: 20
opening page 300
cars found: 20
opening page 301
cars found: 20
opening page 302
cars found: 20
opening page 303
cars found: 20
opening page 304
cars found: 20
opening page 305
cars found: 20
opening page 306
cars found: 20
opening page 307
cars found: 20
opening page 308
cars found: 20
opening page 309
cars found: 20
opening page 310
cars found: 20
opening page 311
cars found: 20
opening page 312
cars found: 20
opening page 313
cars found: 20
opening page 314
cars found: 20
opening page 315
cars found: 20
opening page 316
cars found: 20
opening page 317
cars found: 20
opening page 318
cars found: 20
opening page 319
cars found: 20
opening page 320
cars found: 20
opening page 321
cars found: 20
opening page 322
cars found: 20
opening page 323
cars found: 20
opening page 324
cars found: 20
opening page 325
cars found: 20
opening page 326
cars found: 20
opening page 327
cars found: 20
opening page 328
cars found: 20
opening page 329
cars found: 20
opening page 330
cars found: 20
opening page 331
cars found: 20
opening page 332
cars found: 20
opening page 333
cars found: 20
opening page 334
cars found: 20
opening page 335
cars found: 20
opening page 336
cars found: 20
opening page 337
cars found: 20
opening page 338
cars found: 20
opening page 339
cars found: 20
opening page 340
cars found: 20
opening page 341
cars found: 20
opening page 342
cars found: 20
opening page 343
cars found: 20
opening page 344
cars found: 20
opening page 345
cars found: 20
opening page 346
cars found: 20
opening page 347
cars found: 20
opening page 348
cars found: 20
opening page 349
cars found: 20
opening page 350
cars found: 20
opening page 351
cars found: 20
opening page 352
cars found: 20
opening page 353
cars found: 20
opening page 354
cars found: 20
opening page 355
cars found: 20
opening page 356
cars found: 20
opening page 357
cars found: 20
opening page 358
cars found: 20
opening page 359
cars found: 20
opening page 360
cars found: 20
opening page 361
cars found: 20
opening page 362
cars found: 20
opening page 363
cars found: 20
opening page 364
cars found: 20
opening page 365
cars found: 20
opening page 366
cars found: 20
opening page 367
cars found: 20
opening page 368
cars found: 20
opening page 369
cars found: 20
opening page 370
cars found: 20
opening page 371
cars found: 20
opening page 372
cars found: 20
opening page 373
cars found: 20
opening page 374
cars found: 20
opening page 375
cars found: 20
opening page 376
cars found: 20
opening page 377
cars found: 20
opening page 378
cars found: 20
opening page 379
cars found: 20
opening page 380
cars found: 20
opening page 381
cars found: 20
opening page 382
cars found: 20
opening page 383
cars found: 20
opening page 384
cars found: 20
opening page 385
cars found: 20
opening page 386
cars found: 20
opening page 387
cars found: 20
opening page 388
cars found: 20
opening page 389
cars found: 20
opening page 390
cars found: 20
opening page 391
cars found: 20
opening page 392
cars found: 20
opening page 393
cars found: 20
opening page 394
cars found: 20
opening page 395
cars found: 20
opening page 396
cars found: 20
opening page 397
cars found: 20
opening page 398
cars found: 20
opening page 399
cars found: 20
opening page 400
cars found: 20
opening page 401
cars found: 20
opening page 402
cars found: 20
opening page 403
cars found: 20
opening page 404
cars found: 20
opening page 405
cars found: 20
opening page 406
cars found: 20
opening page 407
cars found: 20
opening page 408
cars found: 20
opening page 409
cars found: 20
opening page 410
cars found: 20
opening page 411
cars found: 20
opening page 412
cars found: 20
opening page 413
cars found: 20
opening page 414
cars found: 20
opening page 415
cars found: 20
opening page 416
cars found: 20
opening page 417
cars found: 20
opening page 418
cars found: 20
opening page 419
cars found: 20
opening page 420
cars found: 20
opening page 421
cars found: 20
opening page 422
cars found: 20
opening page 423
cars found: 20
opening page 424
cars found: 20
opening page 425
cars found: 20
opening page 426
cars found: 20
opening page 427
cars found: 20
opening page 428
cars found: 20
opening page 429
cars found: 20
opening page 430
cars found: 20
opening page 431
cars found: 20
opening page 432
cars found: 20
opening page 433
cars found: 20
opening page 434
cars found: 20
opening page 435
cars found: 20
opening page 436
cars found: 20
opening page 437
cars found: 20
opening page 438
cars found: 20
opening page 439
cars found: 20
opening page 440
cars found: 20
opening page 441
cars found: 20
opening page 442
cars found: 20
opening page 443
cars found: 20
opening page 444
cars found: 20
opening page 445
cars found: 20
opening page 446
cars found: 20
opening page 447
cars found: 20
opening page 448
cars found: 20
opening page 449
cars found: 20
opening page 450
cars found: 20
opening page 451
cars found: 20
opening page 452
cars found: 20
opening page 453
cars found: 20
opening page 454
cars found: 20
opening page 455
cars found: 20
opening page 456
cars found: 20
opening page 457
cars found: 20
opening page 458
cars found: 20
opening page 459
cars found: 20
opening page 460
cars found: 20
opening page 461
cars found: 20
opening page 462
cars found: 20
opening page 463
cars found: 20
opening page 464
cars found: 20
opening page 465
cars found: 20
opening page 466
cars found: 20
opening page 467
cars found: 20
opening page 468
cars found: 20
opening page 469
cars found: 20
opening page 470
cars found: 20
opening page 471
cars found: 20
opening page 472
cars found: 20
opening page 473
cars found: 20
opening page 474
cars found: 20
opening page 475
cars found: 20
opening page 476
cars found: 20
opening page 477
cars found: 20
opening page 478
cars found: 20
opening page 479
cars found: 20
opening page 480
cars found: 20
opening page 481
cars found: 20
opening page 482
cars found: 20
opening page 483
cars found: 20
opening page 484
cars found: 20
opening page 485
cars found: 20
opening page 486
cars found: 20
opening page 487
cars found: 20
opening page 488
cars found: 20
opening page 489
cars found: 20
opening page 490
cars found: 20
opening page 491
cars found: 20
opening page 492
cars found: 20
opening page 493
cars found: 20

In [27]:
df_delhi_ncr = pd.DataFrame(all_cars)
print("Total delhi-ncr cars:", len(df_delhi_ncr))
df_delhi_ncr.head()

Total delhi-ncr cars: 9860

,car_brand,car_name,year,km_driven,fuel,transmission,price,city
0,BMW,BMW 3 Series Long Wheelbase330Li M Sport First...,2021,"9,690kms",Petrol,Automatic,₹38 Lakh,delhi-ncr
1,Mahindra,Mahindra XUV500AT W10 FWD,2017,"1,20,000kms",Diesel,Automatic,₹4.10 Lakh,delhi-ncr
2,BMW,BMW 2 Series Gran Coupe220i M Sport,2025,"3,000kms",Petrol,Automatic,₹39.50 Lakh,delhi-ncr
3,Renault,Renault TriberRXT BSVI,2021,"22,000kms",Petrol,Manual,₹3.50 Lakh,delhi-ncr
4,Maruti,Maruti CelerioZXI BSVI,2022,"24,000kms",Petrol,Manual,₹4.25 Lakh,delhi-ncr

In [28]:
df_delhi_ncr.to_csv(r"C:\Users\admin\Desktop\Used_Cars_ Price_Analysis\data\raw\used_cars_delhi-ncr_raw.csv", index=False)
print("Saved: used_cars_delhi-ncr_raw.csv")

Saved: used_cars_delhi-ncr_raw.csv

# PUNE

In [29]:
all_cars = []
page = 1
max_pages = 120

while page <= max_pages:
    print(f"opening page {page}")

    if page == 1:
        url = "https://www.cardekho.com/used-cars+in+pune"
    else:
        url = f"https://www.cardekho.com/used-cars+in+pune/page-{page}"

    driver.get(url)
    time.sleep(5)

    soup = BeautifulSoup(driver.page_source, "html.parser")
    cards = soup.find_all("div",class_="NewUcExCard")

    print("cars found:",len(cards))

    for card in cards:
        try:
            #--Title--
            title = card.find("h3",class_="title").get_text(strip=True)

            

            #--year--
            year = None
            for y in range(1990, 2027):
                if str(y) in title:
                    year = str(y)
                    title = title.replace(str(y), str(y) + " ")

                    break

            #--car name--
            car_name = title.strip()
            if year:
                car_name = car_name.replace(year, "").strip()

            #--Brand--
            car_brand =  None
            for b in brands:
                if b in title:
                    car_brand = b
                    break

            #--Details--
            details = card.find("div", class_="dotsDetails")
            if details:
                parts = [x.strip() for x in details.get_text(strip=True).split("•")]
                km_driven = parts[0] if len(parts) > 0 else None
                fuel = parts[1] if len(parts) > 1 else None
                transmission = parts[2] if len(parts) > 2 else None
            else:
                km_driven = fuel = transmission = None


            #--price--
            price_tag = card.find("div", class_="priceAssured")
            price = price_tag.get_text(strip=True) if price_tag else None
            
            #---Append---
            all_cars.append({
            "car_brand": car_brand,
            "car_name":car_name,
            "year":year,
            "km_driven":km_driven,
            "fuel":fuel,
            "transmission":transmission,
            "price":price,
            "city":"pune"
            })

        except Exception:
            continue

    page += 1

opening page 1
cars found: 20
opening page 2
cars found: 20
opening page 3
cars found: 20
opening page 4
cars found: 20
opening page 5
cars found: 20
opening page 6
cars found: 20
opening page 7
cars found: 20
opening page 8
cars found: 20
opening page 9
cars found: 20
opening page 10
cars found: 20
opening page 11
cars found: 20
opening page 12
cars found: 20
opening page 13
cars found: 20
opening page 14
cars found: 20
opening page 15
cars found: 20
opening page 16
cars found: 20
opening page 17
cars found: 20
opening page 18
cars found: 20
opening page 19
cars found: 20
opening page 20
cars found: 20
opening page 21
cars found: 20
opening page 22
cars found: 20
opening page 23
cars found: 20
opening page 24
cars found: 20
opening page 25
cars found: 20
opening page 26
cars found: 20
opening page 27
cars found: 20
opening page 28
cars found: 20
opening page 29
cars found: 20
opening page 30
cars found: 20
opening page 31
cars found: 20
opening page 32
cars found: 20
opening page 33
cars found: 20
opening page 34
cars found: 20
opening page 35
cars found: 20
opening page 36
cars found: 20
opening page 37
cars found: 20
opening page 38
cars found: 20
opening page 39
cars found: 20
opening page 40
cars found: 20
opening page 41
cars found: 20
opening page 42
cars found: 20
opening page 43
cars found: 20
opening page 44
cars found: 20
opening page 45
cars found: 20
opening page 46
cars found: 20
opening page 47
cars found: 20
opening page 48
cars found: 20
opening page 49
cars found: 20
opening page 50
cars found: 20
opening page 51
cars found: 20
opening page 52
cars found: 20
opening page 53
cars found: 20
opening page 54
cars found: 20
opening page 55
cars found: 20
opening page 56
cars found: 20
opening page 57
cars found: 20
opening page 58
cars found: 20
opening page 59
cars found: 20
opening page 60
cars found: 20
opening page 61
cars found: 20
opening page 62
cars found: 20
opening page 63
cars found: 20
opening page 64
cars found: 20
opening page 65
cars found: 20
opening page 66
cars found: 20
opening page 67
cars found: 20
opening page 68
cars found: 20
opening page 69
cars found: 20
opening page 70
cars found: 20
opening page 71
cars found: 20
opening page 72
cars found: 20
opening page 73
cars found: 20
opening page 74
cars found: 20
opening page 75
cars found: 20
opening page 76
cars found: 20
opening page 77
cars found: 20
opening page 78
cars found: 20
opening page 79
cars found: 20
opening page 80
cars found: 20
opening page 81
cars found: 20
opening page 82
cars found: 20
opening page 83
cars found: 20
opening page 84
cars found: 20
opening page 85
cars found: 20
opening page 86
cars found: 20
opening page 87
cars found: 20
opening page 88
cars found: 20
opening page 89
cars found: 20
opening page 90
cars found: 20
opening page 91
cars found: 20
opening page 92
cars found: 20
opening page 93
cars found: 20
opening page 94
cars found: 20
opening page 95
cars found: 20
opening page 96
cars found: 20
opening page 97
cars found: 20
opening page 98
cars found: 20
opening page 99
cars found: 20
opening page 100
cars found: 20
opening page 101
cars found: 20
opening page 102
cars found: 20
opening page 103
cars found: 20
opening page 104
cars found: 20
opening page 105
cars found: 20
opening page 106
cars found: 20
opening page 107
cars found: 20
opening page 108
cars found: 20
opening page 109
cars found: 20
opening page 110
cars found: 20
opening page 111
cars found: 20
opening page 112
cars found: 20
opening page 113
cars found: 20
opening page 114
cars found: 20
opening page 115
cars found: 20
opening page 116
cars found: 20
opening page 117
cars found: 20
opening page 118
cars found: 20
opening page 119
cars found: 20
opening page 120
cars found: 20

In [30]:
df_pune = pd.DataFrame(all_cars)
print("Total pune cars:", len(df_pune))
df_pune.head()

Total pune cars: 2400

,car_brand,car_name,year,km_driven,fuel,transmission,price,city
0,Skoda,Skoda Slavia1.0 TSI Style AT BSVI,2023,"13,200kms",Petrol,Automatic,₹13.95 Lakh,pune
1,Jeep,Jeep Compass2.0 Limited 4X4 Opt Diesel AT BSVI,2021,"72,000kms",Diesel,Automatic,₹22 Lakh,pune
2,Volkswagen,Volkswagen VentoPetrol Highline,2011,"88,000kms",Petrol,Manual,₹2.49 Lakh,pune
3,Honda,Honda AmazeS i-VTEC,2014,"1,41,486kms",Petrol,Manual,₹2.95 Lakh,pune
4,MG,MG ZS EVExclusive,2022,"19,800kms",Electric,Automatic,₹18 Lakh,pune

In [31]:
df_pune.to_csv(r"C:\Users\admin\Desktop\Used_Cars_ Price_Analysis\data\raw\used_cars_pune_raw.csv", index=False)
print("Saved: used_cars_pune_raw.csv")

Saved: used_cars_pune_raw.csv

# Ahmedabad

In [32]:
all_cars = []
page = 1
max_pages = 84

while page <= max_pages:
    print(f"opening page {page}")

    if page == 1:
        url = "https://www.cardekho.com/used-cars+in+ahmedabad"
    else:
        url = f"https://www.cardekho.com/used-cars+in+ahmedabad/page-{page}"

    driver.get(url)
    time.sleep(5)

    soup = BeautifulSoup(driver.page_source, "html.parser")
    cards = soup.find_all("div",class_="NewUcExCard")

    print("cars found:",len(cards))

    for card in cards:
        try:
            #--Title--
            title = card.find("h3",class_="title").get_text(strip=True)

            

            #--year--
            year = None
            for y in range(1990, 2027):
                if str(y) in title:
                    year = str(y)
                    title = title.replace(str(y), str(y) + " ")

                    break

            #--car name--
            car_name = title.strip()
            if year:
                car_name = car_name.replace(year, "").strip()

            #--Brand--
            car_brand =  None
            for b in brands:
                if b in title:
                    car_brand = b
                    break

            #--Details--
            details = card.find("div", class_="dotsDetails")
            if details:
                parts = [x.strip() for x in details.get_text(strip=True).split("•")]
                km_driven = parts[0] if len(parts) > 0 else None
                fuel = parts[1] if len(parts) > 1 else None
                transmission = parts[2] if len(parts) > 2 else None
            else:
                km_driven = fuel = transmission = None


            #--price--
            price_tag = card.find("div", class_="priceAssured")
            price = price_tag.get_text(strip=True) if price_tag else None
            
            #---Append---
            all_cars.append({
            "car_brand": car_brand,
            "car_name":car_name,
            "year":year,
            "km_driven":km_driven,
            "fuel":fuel,
            "transmission":transmission,
            "price":price,
            "city":"ahmedabad"
            })

        except Exception:
            continue

    page += 1

opening page 1
cars found: 20
opening page 2
cars found: 20
opening page 3
cars found: 20
opening page 4
cars found: 20
opening page 5
cars found: 20
opening page 6
cars found: 20
opening page 7
cars found: 20
opening page 8
cars found: 20
opening page 9
cars found: 20
opening page 10
cars found: 20
opening page 11
cars found: 20
opening page 12
cars found: 20
opening page 13
cars found: 20
opening page 14
cars found: 20
opening page 15
cars found: 20
opening page 16
cars found: 20
opening page 17
cars found: 20
opening page 18
cars found: 20
opening page 19
cars found: 20
opening page 20
cars found: 20
opening page 21
cars found: 20
opening page 22
cars found: 20
opening page 23
cars found: 20
opening page 24
cars found: 20
opening page 25
cars found: 20
opening page 26
cars found: 20
opening page 27
cars found: 20
opening page 28
cars found: 20
opening page 29
cars found: 20
opening page 30
cars found: 20
opening page 31
cars found: 20
opening page 32
cars found: 20
opening page 33
cars found: 20
opening page 34
cars found: 20
opening page 35
cars found: 20
opening page 36
cars found: 20
opening page 37
cars found: 20
opening page 38
cars found: 20
opening page 39
cars found: 20
opening page 40
cars found: 20
opening page 41
cars found: 20
opening page 42
cars found: 20
opening page 43
cars found: 20
opening page 44
cars found: 20
opening page 45
cars found: 20
opening page 46
cars found: 20
opening page 47
cars found: 20
opening page 48
cars found: 20
opening page 49
cars found: 20
opening page 50
cars found: 20
opening page 51
cars found: 20
opening page 52
cars found: 20
opening page 53
cars found: 20
opening page 54
cars found: 20
opening page 55
cars found: 20
opening page 56
cars found: 20
opening page 57
cars found: 20
opening page 58
cars found: 20
opening page 59
cars found: 20
opening page 60
cars found: 20
opening page 61
cars found: 20
opening page 62
cars found: 20
opening page 63
cars found: 20
opening page 64
cars found: 20
opening page 65
cars found: 20
opening page 66
cars found: 20
opening page 67
cars found: 20
opening page 68
cars found: 20
opening page 69
cars found: 20
opening page 70
cars found: 20
opening page 71
cars found: 20
opening page 72
cars found: 20
opening page 73
cars found: 20
opening page 74
cars found: 20
opening page 75
cars found: 20
opening page 76
cars found: 20
opening page 77
cars found: 20
opening page 78
cars found: 20
opening page 79
cars found: 20
opening page 80
cars found: 20
opening page 81
cars found: 20
opening page 82
cars found: 20
opening page 83
cars found: 20
opening page 84
cars found: 20

In [33]:
df_ahmedabad = pd.DataFrame(all_cars)
print("Total ahmedabad cars:", len(df_ahmedabad))
df_ahmedabad.head()

Total ahmedabad cars: 1680

,car_brand,car_name,year,km_driven,fuel,transmission,price,city
0,Hyundai,Hyundai i20Asta,2023,"9,800kms",Petrol,Manual,₹7.70 Lakh,ahmedabad
1,Hyundai,Hyundai i20Sportz Plus Dual Tone BSIV,2019,"22,371kms",Petrol,Manual,₹5.29 Lakh,ahmedabad
2,Nissan,Nissan MagniteTurbo XV BSVI,2021,"99,687kms",Petrol,Manual,₹4.50 Lakh,ahmedabad
3,Maruti,Maruti SwiftVXI,2019,"40,477kms",Petrol,Manual,₹4.47 Lakh,ahmedabad
4,Jeep,Jeep Compass2.0 Limited,2017,"1,80,000kms",Diesel,Manual,₹6.50 Lakh,ahmedabad

In [34]:
df_ahmedabad.to_csv(r"C:\Users\admin\Desktop\Used_Cars_ Price_Analysis\data\raw\used_cars_ahmedabad_raw.csv", index=False)
print("Saved: used_cars_ahmedabad_raw.csv")

Saved: used_cars_ahmedabad_raw.csv

# Chandigarh

In [35]:
all_cars = []
page = 1
max_pages = 23

while page <= max_pages:
    print(f"opening page {page}")

    if page == 1:
        url = "https://www.cardekho.com/used-cars+in+chandigarh"
    else:
        url = f"https://www.cardekho.com/used-cars+in+chandigarh/page-{page}"

    driver.get(url)
    time.sleep(5)

    soup = BeautifulSoup(driver.page_source, "html.parser")
    cards = soup.find_all("div",class_="NewUcExCard")

    print("cars found:",len(cards))

    for card in cards:
        try:
            #--Title--
            title = card.find("h3",class_="title").get_text(strip=True)

            

            #--year--
            year = None
            for y in range(1990, 2027):
                if str(y) in title:
                    year = str(y)
                    title = title.replace(str(y), str(y) + " ")

                    break
                    
            #--car name--
            car_name = title.strip()
            if year:
                car_name = car_name.replace(year, "").strip()

            #--Brand--
            car_brand =  None
            for b in brands:
                if b in title:
                    car_brand = b
                    break

            #--Details--
            details = card.find("div", class_="dotsDetails")
            if details:
                parts = [x.strip() for x in details.get_text(strip=True).split("•")]
                km_driven = parts[0] if len(parts) > 0 else None
                fuel = parts[1] if len(parts) > 1 else None
                transmission = parts[2] if len(parts) > 2 else None
            else:
                km_driven = fuel = transmission = None


            #--price--
            price_tag = card.find("div", class_="priceAssured")
            price = price_tag.get_text(strip=True) if price_tag else None
            
            #---Append---
            all_cars.append({
            "car_brand": car_brand,
            "car_name":car_name,
            "year":year,
            "km_driven":km_driven,
            "fuel":fuel,
            "transmission":transmission,
            "price":price,
            "city":"chandigarh"
            })

        except Exception:
            continue

    page += 1

opening page 1
cars found: 20
opening page 2
cars found: 20
opening page 3
cars found: 20
opening page 4
cars found: 20
opening page 5
cars found: 20
opening page 6
cars found: 20
opening page 7
cars found: 20
opening page 8
cars found: 20
opening page 9
cars found: 20
opening page 10
cars found: 20
opening page 11
cars found: 20
opening page 12
cars found: 20
opening page 13
cars found: 20
opening page 14
cars found: 20
opening page 15
cars found: 20
opening page 16
cars found: 20
opening page 17
cars found: 20
opening page 18
cars found: 20
opening page 19
cars found: 20
opening page 20
cars found: 20
opening page 21
cars found: 20
opening page 22
cars found: 20
opening page 23
cars found: 20

In [36]:
df_chandigarh = pd.DataFrame(all_cars)
print("Total chandigarh cars:", len(df_chandigarh))
df_chandigarh.head()

Total chandigarh cars: 460

,car_brand,car_name,year,km_driven,fuel,transmission,price,city
0,Tata,Tata Tiago EVXZ Plus LR,2024,"25,942kms",Electric,Automatic,₹8.50 Lakh,chandigarh
1,Hyundai,Hyundai i20Sportz 1.2,2017,"27,368kms",Petrol,Manual,₹5.10 Lakh,chandigarh
2,Honda,Honda AmazeVX CVT Petrol,2022,"35,944kms",Petrol,Automatic,₹6.92 Lakh,chandigarh
3,Maruti,Maruti BalenoAlpha AMT,2022,"67,281kms",Petrol,Automatic,₹6.45 Lakh,chandigarh
4,MG,MG GlosterSavvy 4x4 6Str,2023,"65,000kms",Diesel,Automatic,₹35 Lakh,chandigarh

In [37]:
df_chandigarh.to_csv(r"C:\Users\admin\Desktop\Used_Cars_ Price_Analysis\data\raw\used_cars_chandigarh_raw.csv", index=False)
print("Saved: used_cars_chandigarh_raw.csv")

Saved: used_cars_chandigarh_raw.csv

# Gurgaon

In [38]:
all_cars = []
page = 1
max_pages = 167

while page <= max_pages:
    print(f"opening page {page}")

    if page == 1:
        url = "https://www.cardekho.com/used-cars+in+gurgaon"
    else:
        url = f"https://www.cardekho.com/used-cars+in+gurgaon/page-{page}"

    driver.get(url)
    time.sleep(5)

    soup = BeautifulSoup(driver.page_source, "html.parser")
    cards = soup.find_all("div",class_="NewUcExCard")

    print("cars found:",len(cards))

    for card in cards:
        try:
            #--Title--
            title = card.find("h3",class_="title").get_text(strip=True)

            

            #--year--
            year = None
            for y in range(1990, 2027):
                if str(y) in title:
                    year = str(y)
                    title = title.replace(str(y), str(y) + " ")

                    break

            #--car name--
            car_name = title.strip()
            if year:
                car_name = car_name.replace(year, "").strip()

            #--Brand--
            car_brand =  None
            for b in brands:
                if b in title:
                    car_brand = b
                    break

            #--Details--
            details = card.find("div", class_="dotsDetails")
            if details:
                parts = [x.strip() for x in details.get_text(strip=True).split("•")]
                km_driven = parts[0] if len(parts) > 0 else None
                fuel = parts[1] if len(parts) > 1 else None
                transmission = parts[2] if len(parts) > 2 else None
            else:
                km_driven = fuel = transmission = None


            #--price--
            price_tag = card.find("div", class_="priceAssured")
            price = price_tag.get_text(strip=True) if price_tag else None
            
            #---Append---
            all_cars.append({
            "car_brand": car_brand,
            "car_name":car_name,
            "year":year,
            "km_driven":km_driven,
            "fuel":fuel,
            "transmission":transmission,
            "price":price,
            "city":"gurgaon"
            })

        except Exception:
            continue

    page += 1

opening page 1
cars found: 20
opening page 2
cars found: 20
opening page 3
cars found: 20
opening page 4
cars found: 20
opening page 5
cars found: 20
opening page 6
cars found: 20
opening page 7
cars found: 20
opening page 8
cars found: 20
opening page 9
cars found: 20
opening page 10
cars found: 20
opening page 11
cars found: 20
opening page 12
cars found: 20
opening page 13
cars found: 20
opening page 14
cars found: 20
opening page 15
cars found: 20
opening page 16
cars found: 20
opening page 17
cars found: 20
opening page 18
cars found: 20
opening page 19
cars found: 20
opening page 20
cars found: 20
opening page 21
cars found: 20
opening page 22
cars found: 20
opening page 23
cars found: 20
opening page 24
cars found: 20
opening page 25
cars found: 20
opening page 26
cars found: 20
opening page 27
cars found: 20
opening page 28
cars found: 20
opening page 29
cars found: 20
opening page 30
cars found: 20
opening page 31
cars found: 20
opening page 32
cars found: 20
opening page 33
cars found: 20
opening page 34
cars found: 20
opening page 35
cars found: 20
opening page 36
cars found: 20
opening page 37
cars found: 20
opening page 38
cars found: 20
opening page 39
cars found: 20
opening page 40
cars found: 20
opening page 41
cars found: 20
opening page 42
cars found: 20
opening page 43
cars found: 20
opening page 44
cars found: 20
opening page 45
cars found: 20
opening page 46
cars found: 20
opening page 47
cars found: 20
opening page 48
cars found: 20
opening page 49
cars found: 20
opening page 50
cars found: 20
opening page 51
cars found: 20
opening page 52
cars found: 20
opening page 53
cars found: 20
opening page 54
cars found: 20
opening page 55
cars found: 20
opening page 56
cars found: 20
opening page 57
cars found: 20
opening page 58
cars found: 20
opening page 59
cars found: 20
opening page 60
cars found: 20
opening page 61
cars found: 20
opening page 62
cars found: 20
opening page 63
cars found: 20
opening page 64
cars found: 20
opening page 65
cars found: 20
opening page 66
cars found: 20
opening page 67
cars found: 20
opening page 68
cars found: 20
opening page 69
cars found: 20
opening page 70
cars found: 20
opening page 71
cars found: 20
opening page 72
cars found: 20
opening page 73
cars found: 20
opening page 74
cars found: 20
opening page 75
cars found: 20
opening page 76
cars found: 20
opening page 77
cars found: 20
opening page 78
cars found: 20
opening page 79
cars found: 20
opening page 80
cars found: 20
opening page 81
cars found: 20
opening page 82
cars found: 20
opening page 83
cars found: 20
opening page 84
cars found: 20
opening page 85
cars found: 20
opening page 86
cars found: 20
opening page 87
cars found: 20
opening page 88
cars found: 20
opening page 89
cars found: 20
opening page 90
cars found: 20
opening page 91
cars found: 20
opening page 92
cars found: 20
opening page 93
cars found: 20
opening page 94
cars found: 20
opening page 95
cars found: 20
opening page 96
cars found: 20
opening page 97
cars found: 20
opening page 98
cars found: 20
opening page 99
cars found: 20
opening page 100
cars found: 20
opening page 101
cars found: 20
opening page 102
cars found: 20
opening page 103
cars found: 20
opening page 104
cars found: 20
opening page 105
cars found: 20
opening page 106
cars found: 20
opening page 107
cars found: 20
opening page 108
cars found: 20
opening page 109
cars found: 20
opening page 110
cars found: 20
opening page 111
cars found: 20
opening page 112
cars found: 20
opening page 113
cars found: 20
opening page 114
cars found: 20
opening page 115
cars found: 20
opening page 116
cars found: 20
opening page 117
cars found: 20
opening page 118
cars found: 20
opening page 119
cars found: 20
opening page 120
cars found: 20
opening page 121
cars found: 20
opening page 122
cars found: 20
opening page 123
cars found: 20
opening page 124
cars found: 20
opening page 125
cars found: 20
opening page 126
cars found: 20
opening page 127
cars found: 20
opening page 128
cars found: 20
opening page 129
cars found: 20
opening page 130
cars found: 20
opening page 131
cars found: 20
opening page 132
cars found: 20
opening page 133
cars found: 20
opening page 134
cars found: 20
opening page 135
cars found: 20
opening page 136
cars found: 20
opening page 137
cars found: 20
opening page 138
cars found: 20
opening page 139
cars found: 20
opening page 140
cars found: 20
opening page 141
cars found: 20
opening page 142
cars found: 20
opening page 143
cars found: 20
opening page 144
cars found: 20
opening page 145
cars found: 20
opening page 146
cars found: 20
opening page 147
cars found: 20
opening page 148
cars found: 20
opening page 149
cars found: 20
opening page 150
cars found: 20
opening page 151
cars found: 20
opening page 152
cars found: 20
opening page 153
cars found: 20
opening page 154
cars found: 20
opening page 155
cars found: 20
opening page 156
cars found: 20
opening page 157
cars found: 20
opening page 158
cars found: 20
opening page 159
cars found: 20
opening page 160
cars found: 20
opening page 161
cars found: 20
opening page 162
cars found: 20
opening page 163
cars found: 20
opening page 164
cars found: 20
opening page 165
cars found: 20
opening page 166
cars found: 20
opening page 167
cars found: 20

In [39]:
df_gurgaon = pd.DataFrame(all_cars)
print("Total gurgaon cars:", len(df_gurgaon))
df_gurgaon.head()

Total gurgaon cars: 3340

,car_brand,car_name,year,km_driven,fuel,transmission,price,city
0,Land Rover,Land Rover Range Rover3.0 Diesel LWB Vogue,2021,"48,554kms",Diesel,Automatic,₹1.40 Crore,gurgaon
1,BMW,BMW iXxDrive50,2024,"4,002kms",Electric,Automatic,₹92 Lakh,gurgaon
2,Toyota,Toyota Land Cruiser 200VX,2017,"1,30,000kms",Diesel,Automatic,₹1.20 Crore,gurgaon
3,Lexus,2021Lexus ES300h Luxury -2022,2020,"80,000kms",Petrol,Automatic,₹32 Lakh,gurgaon
4,Toyota,Toyota Land Cruiser 200VX,2017,"2,60,000kms",Diesel,Automatic,₹96 Lakh,gurgaon

In [40]:
df_gurgaon.to_csv(r"C:\Users\admin\Desktop\Used_Cars_ Price_Analysis\data\raw\used_cars_gurgaon_raw.csv", index=False)
print("Saved: used_cars_gurgaon_raw.csv")

Saved: used_cars_gurgaon_raw.csv

# Jaipur

In [41]:
all_cars = []
page = 1
max_pages = 65

while page <= max_pages:
    print(f"opening page {page}")

    if page == 1:
        url = "https://www.cardekho.com/used-cars+in+jaipur"
    else:
        url = f"https://www.cardekho.com/used-cars+in+jaipur/page-{page}"

    driver.get(url)
    time.sleep(5)

    soup = BeautifulSoup(driver.page_source, "html.parser")
    cards = soup.find_all("div",class_="NewUcExCard")

    print("cars found:",len(cards))

    for card in cards:
        try:
            #--Title--
            title = card.find("h3",class_="title").get_text(strip=True)

             

            #--year--
            year = None
            for y in range(1990, 2027):
                if str(y) in title:
                    year = str(y)
                    title = title.replace(str(y), str(y) + " ")

                    break

            #--car name--
            car_name = title.strip()
            if year:
                car_name = car_name.replace(year, "").strip()

            #--Brand--
            car_brand =  None
            for b in brands:
                if b in title:
                    car_brand = b
                    break

            #--Details--
            details = card.find("div", class_="dotsDetails")
            if details:
                parts = [x.strip() for x in details.get_text(strip=True).split("•")]
                km_driven = parts[0] if len(parts) > 0 else None
                fuel = parts[1] if len(parts) > 1 else None
                transmission = parts[2] if len(parts) > 2 else None
            else:
                km_driven = fuel = transmission = None


            #--price--
            price_tag = card.find("div", class_="priceAssured")
            price = price_tag.get_text(strip=True) if price_tag else None
            
            #---Append---
            all_cars.append({
            "car_brand": car_brand,
            "car_name":car_name,
            "year":year,
            "km_driven":km_driven,
            "fuel":fuel,
            "transmission":transmission,
            "price":price,
            "city":"jaipur"
            })

        except Exception:
            continue

    page += 1

opening page 1
cars found: 20
opening page 2
cars found: 20
opening page 3
cars found: 20
opening page 4
cars found: 20
opening page 5
cars found: 20
opening page 6
cars found: 20
opening page 7
cars found: 20
opening page 8
cars found: 20
opening page 9
cars found: 20
opening page 10
cars found: 20
opening page 11
cars found: 20
opening page 12
cars found: 20
opening page 13
cars found: 20
opening page 14
cars found: 20
opening page 15
cars found: 20
opening page 16
cars found: 20
opening page 17
cars found: 20
opening page 18
cars found: 20
opening page 19
cars found: 20
opening page 20
cars found: 20
opening page 21
cars found: 20
opening page 22
cars found: 20
opening page 23
cars found: 20
opening page 24
cars found: 20
opening page 25
cars found: 20
opening page 26
cars found: 20
opening page 27
cars found: 20
opening page 28
cars found: 20
opening page 29
cars found: 20
opening page 30
cars found: 20
opening page 31
cars found: 20
opening page 32
cars found: 20
opening page 33
cars found: 20
opening page 34
cars found: 20
opening page 35
cars found: 20
opening page 36
cars found: 20
opening page 37
cars found: 20
opening page 38
cars found: 20
opening page 39
cars found: 20
opening page 40
cars found: 20
opening page 41
cars found: 20
opening page 42
cars found: 20
opening page 43
cars found: 20
opening page 44
cars found: 20
opening page 45
cars found: 20
opening page 46
cars found: 20
opening page 47
cars found: 20
opening page 48
cars found: 20
opening page 49
cars found: 20
opening page 50
cars found: 20
opening page 51
cars found: 20
opening page 52
cars found: 20
opening page 53
cars found: 20
opening page 54
cars found: 20
opening page 55
cars found: 20
opening page 56
cars found: 20
opening page 57
cars found: 20
opening page 58
cars found: 20
opening page 59
cars found: 20
opening page 60
cars found: 20
opening page 61
cars found: 20
opening page 62
cars found: 20
opening page 63
cars found: 20
opening page 64
cars found: 20
opening page 65
cars found: 20

In [42]:
df_jaipur = pd.DataFrame(all_cars)
print("Total jaipur cars:", len(df_jaipur))
df_jaipur.head()

Total jaipur cars: 1300

,car_brand,car_name,year,km_driven,fuel,transmission,price,city
0,Mercedes-Benz,Mercedes-Benz S-ClassS 350 d,2021,"34,000kms",Diesel,Automatic,₹99 Lakh,jaipur
1,Tata,Tata BoltRevotron XMS,2015,"65,000kms",Petrol,Manual,₹2.70 Lakh,jaipur
2,Maruti,Maruti Wagon RVXI BS IV,2014,"80,000kms",Petrol,Manual,₹2.75 Lakh,jaipur
3,Ford,Ford EcosportTitanium,2020,"32,263kms",Petrol,Manual,₹6.62 Lakh,jaipur
4,Mahindra,Mahindra Scorpio NZ8 Select,2024,"15,000kms",Petrol,Manual,₹17.50 Lakh,jaipur

In [43]:
df_jaipur.to_csv(r"C:\Users\admin\Desktop\Used_Cars_ Price_Analysis\data\raw\used_cars_jaipur_raw.csv", index=False)
print("Saved: used_cars_jaipur_raw.csv")

Saved: used_cars_jaipur_raw.csv

# New-Delhi

In [44]:
all_cars = []
page = 1
max_pages = 332

while page <= max_pages:
    print(f"opening page {page}")

    if page == 1:
        url = "https://www.cardekho.com/used-cars+in+new-delhi"
    else:
        url = f"https://www.cardekho.com/used-cars+in+new-delhi/page-{page}"

    driver.get(url)
    time.sleep(5)

    soup = BeautifulSoup(driver.page_source, "html.parser")
    cards = soup.find_all("div",class_="NewUcExCard")

    print("cars found:",len(cards))

    for card in cards:
        try:
            #--Title--
            title = card.find("h3",class_="title").get_text(strip=True)

            #--year--
            year = None
            for y in range(1990, 2027):
                if str(y) in title:
                    year = str(y)
                    title = title.replace(str(y), str(y) + " ")

                    break

            #--car name--
            car_name = title.strip()
            if year:
                car_name = car_name.replace(year, "").strip()

            #--Brand--
            car_brand =  None
            for b in brands:
                if b in title:
                    car_brand = b
                    break

            #--Details--
            details = card.find("div", class_="dotsDetails")
            if details:
                parts = [x.strip() for x in details.get_text(strip=True).split("•")]
                km_driven = parts[0] if len(parts) > 0 else None
                fuel = parts[1] if len(parts) > 1 else None
                transmission = parts[2] if len(parts) > 2 else None
            else:
                km_driven = fuel = transmission = None


            #--price--
            price_tag = card.find("div", class_="priceAssured")
            price = price_tag.get_text(strip=True) if price_tag else None
            
            #---Append---
            all_cars.append({
            "car_brand": car_brand,
            "car_name":car_name,
            "year":year,
            "km_driven":km_driven,
            "fuel":fuel,
            "transmission":transmission,
            "price":price,
            "city":"new-delhi"
            })

        except Exception:
            continue

    page += 1

opening page 1
cars found: 20
opening page 2
cars found: 20
opening page 3
cars found: 20
opening page 4
cars found: 20
opening page 5
cars found: 20
opening page 6
cars found: 20
opening page 7
cars found: 20
opening page 8
cars found: 20
opening page 9
cars found: 20
opening page 10
cars found: 20
opening page 11
cars found: 20
opening page 12
cars found: 20
opening page 13
cars found: 20
opening page 14
cars found: 20
opening page 15
cars found: 20
opening page 16
cars found: 20
opening page 17
cars found: 20
opening page 18
cars found: 20
opening page 19
cars found: 20
opening page 20
cars found: 20
opening page 21
cars found: 20
opening page 22
cars found: 20
opening page 23
cars found: 20
opening page 24
cars found: 20
opening page 25
cars found: 20
opening page 26
cars found: 20
opening page 27
cars found: 20
opening page 28
cars found: 20
opening page 29
cars found: 20
opening page 30
cars found: 20
opening page 31
cars found: 20
opening page 32
cars found: 20
opening page 33
cars found: 20
opening page 34
cars found: 20
opening page 35
cars found: 20
opening page 36
cars found: 20
opening page 37
cars found: 20
opening page 38
cars found: 20
opening page 39
cars found: 20
opening page 40
cars found: 20
opening page 41
cars found: 20
opening page 42
cars found: 20
opening page 43
cars found: 20
opening page 44
cars found: 20
opening page 45
cars found: 20
opening page 46
cars found: 20
opening page 47
cars found: 20
opening page 48
cars found: 20
opening page 49
cars found: 20
opening page 50
cars found: 20
opening page 51
cars found: 20
opening page 52
cars found: 20
opening page 53
cars found: 20
opening page 54
cars found: 20
opening page 55
cars found: 20
opening page 56
cars found: 20
opening page 57
cars found: 20
opening page 58
cars found: 20
opening page 59
cars found: 20
opening page 60
cars found: 20
opening page 61
cars found: 20
opening page 62
cars found: 20
opening page 63
cars found: 20
opening page 64
cars found: 20
opening page 65
cars found: 20
opening page 66
cars found: 20
opening page 67
cars found: 20
opening page 68
cars found: 20
opening page 69
cars found: 20
opening page 70
cars found: 20
opening page 71
cars found: 20
opening page 72
cars found: 20
opening page 73
cars found: 20
opening page 74
cars found: 20
opening page 75
cars found: 20
opening page 76
cars found: 20
opening page 77
cars found: 20
opening page 78
cars found: 20
opening page 79
cars found: 20
opening page 80
cars found: 20
opening page 81
cars found: 20
opening page 82
cars found: 20
opening page 83
cars found: 20
opening page 84
cars found: 20
opening page 85
cars found: 20
opening page 86
cars found: 20
opening page 87
cars found: 20
opening page 88
cars found: 20
opening page 89
cars found: 20
opening page 90
cars found: 20
opening page 91
cars found: 20
opening page 92
cars found: 20
opening page 93
cars found: 20
opening page 94
cars found: 20
opening page 95
cars found: 20
opening page 96
cars found: 20
opening page 97
cars found: 20
opening page 98
cars found: 20
opening page 99
cars found: 20
opening page 100
cars found: 20
opening page 101
cars found: 20
opening page 102
cars found: 20
opening page 103
cars found: 20
opening page 104
cars found: 20
opening page 105
cars found: 20
opening page 106
cars found: 20
opening page 107
cars found: 20
opening page 108
cars found: 20
opening page 109
cars found: 20
opening page 110
cars found: 20
opening page 111
cars found: 20
opening page 112
cars found: 20
opening page 113
cars found: 20
opening page 114
cars found: 20
opening page 115
cars found: 20
opening page 116
cars found: 20
opening page 117
cars found: 20
opening page 118
cars found: 20
opening page 119
cars found: 20
opening page 120
cars found: 20
opening page 121
cars found: 20
opening page 122
cars found: 20
opening page 123
cars found: 20
opening page 124
cars found: 20
opening page 125
cars found: 20
opening page 126
cars found: 20
opening page 127
cars found: 20
opening page 128
cars found: 20
opening page 129
cars found: 20
opening page 130
cars found: 20
opening page 131
cars found: 20
opening page 132
cars found: 20
opening page 133
cars found: 20
opening page 134
cars found: 20
opening page 135
cars found: 20
opening page 136
cars found: 20
opening page 137
cars found: 20
opening page 138
cars found: 20
opening page 139
cars found: 20
opening page 140
cars found: 20
opening page 141
cars found: 20
opening page 142
cars found: 20
opening page 143
cars found: 20
opening page 144
cars found: 20
opening page 145
cars found: 20
opening page 146
cars found: 20
opening page 147
cars found: 20
opening page 148
cars found: 20
opening page 149
cars found: 20
opening page 150
cars found: 20
opening page 151
cars found: 20
opening page 152
cars found: 20
opening page 153
cars found: 20
opening page 154
cars found: 20
opening page 155
cars found: 20
opening page 156
cars found: 20
opening page 157
cars found: 20
opening page 158
cars found: 20
opening page 159
cars found: 20
opening page 160
cars found: 20
opening page 161
cars found: 20
opening page 162
cars found: 20
opening page 163
cars found: 20
opening page 164
cars found: 20
opening page 165
cars found: 20
opening page 166
cars found: 20
opening page 167
cars found: 20
opening page 168
cars found: 20
opening page 169
cars found: 20
opening page 170
cars found: 20
opening page 171
cars found: 20
opening page 172
cars found: 20
opening page 173
cars found: 20
opening page 174
cars found: 20
opening page 175
cars found: 20
opening page 176
cars found: 20
opening page 177
cars found: 20
opening page 178
cars found: 20
opening page 179
cars found: 20
opening page 180
cars found: 20
opening page 181
cars found: 20
opening page 182
cars found: 20
opening page 183
cars found: 20
opening page 184
cars found: 20
opening page 185
cars found: 20
opening page 186
cars found: 20
opening page 187
cars found: 20
opening page 188
cars found: 20
opening page 189
cars found: 20
opening page 190
cars found: 20
opening page 191
cars found: 20
opening page 192
cars found: 20
opening page 193
cars found: 20
opening page 194
cars found: 20
opening page 195
cars found: 20
opening page 196
cars found: 20
opening page 197
cars found: 20
opening page 198
cars found: 20
opening page 199
cars found: 20
opening page 200
cars found: 20
opening page 201
cars found: 20
opening page 202
cars found: 20
opening page 203
cars found: 20
opening page 204
cars found: 20
opening page 205
cars found: 20
opening page 206
cars found: 20
opening page 207
cars found: 20
opening page 208
cars found: 20
opening page 209
cars found: 20
opening page 210
cars found: 20
opening page 211
cars found: 20
opening page 212
cars found: 20
opening page 213
cars found: 20
opening page 214
cars found: 20
opening page 215
cars found: 20
opening page 216
cars found: 20
opening page 217
cars found: 20
opening page 218
cars found: 20
opening page 219
cars found: 20
opening page 220
cars found: 20
opening page 221
cars found: 20
opening page 222
cars found: 20
opening page 223
cars found: 20
opening page 224
cars found: 20
opening page 225
cars found: 20
opening page 226
cars found: 20
opening page 227
cars found: 20
opening page 228
cars found: 20
opening page 229
cars found: 20
opening page 230
cars found: 20
opening page 231
cars found: 20
opening page 232
cars found: 20
opening page 233
cars found: 20
opening page 234
cars found: 20
opening page 235
cars found: 20
opening page 236
cars found: 20
opening page 237
cars found: 20
opening page 238
cars found: 20
opening page 239
cars found: 20
opening page 240
cars found: 20
opening page 241
cars found: 20
opening page 242
cars found: 20
opening page 243
cars found: 20
opening page 244
cars found: 20
opening page 245
cars found: 20
opening page 246
cars found: 20
opening page 247
cars found: 20
opening page 248
cars found: 20
opening page 249
cars found: 20
opening page 250
cars found: 20
opening page 251
cars found: 20
opening page 252
cars found: 20
opening page 253
cars found: 20
opening page 254
cars found: 20
opening page 255
cars found: 20
opening page 256
cars found: 20
opening page 257
cars found: 20
opening page 258
cars found: 20
opening page 259
cars found: 20
opening page 260
cars found: 20
opening page 261
cars found: 20
opening page 262
cars found: 20
opening page 263
cars found: 20
opening page 264
cars found: 20
opening page 265
cars found: 20
opening page 266
cars found: 20
opening page 267
cars found: 20
opening page 268
cars found: 20
opening page 269
cars found: 20
opening page 270
cars found: 20
opening page 271
cars found: 20
opening page 272
cars found: 20
opening page 273
cars found: 20
opening page 274
cars found: 20
opening page 275
cars found: 20
opening page 276
cars found: 20
opening page 277
cars found: 20
opening page 278
cars found: 20
opening page 279
cars found: 20
opening page 280
cars found: 20
opening page 281
cars found: 20
opening page 282
cars found: 20
opening page 283
cars found: 20
opening page 284
cars found: 20
opening page 285
cars found: 20
opening page 286
cars found: 20
opening page 287
cars found: 20
opening page 288
cars found: 20
opening page 289
cars found: 20
opening page 290
cars found: 20
opening page 291
cars found: 20
opening page 292
cars found: 20
opening page 293
cars found: 20
opening page 294
cars found: 20
opening page 295
cars found: 20
opening page 296
cars found: 20
opening page 297
cars found: 20
opening page 298
cars found: 20
opening page 299
cars found: 20
opening page 300
cars found: 20
opening page 301
cars found: 20
opening page 302
cars found: 20
opening page 303
cars found: 20
opening page 304
cars found: 20
opening page 305
cars found: 20
opening page 306
cars found: 20
opening page 307
cars found: 20
opening page 308
cars found: 20
opening page 309
cars found: 20
opening page 310
cars found: 20
opening page 311
cars found: 20
opening page 312
cars found: 20
opening page 313
cars found: 20
opening page 314
cars found: 20
opening page 315
cars found: 20
opening page 316
cars found: 20
opening page 317
cars found: 20
opening page 318
cars found: 20
opening page 319
cars found: 20
opening page 320
cars found: 20
opening page 321
cars found: 20
opening page 322
cars found: 20
opening page 323
cars found: 20
opening page 324
cars found: 20
opening page 325
cars found: 20
opening page 326
cars found: 20
opening page 327
cars found: 20
opening page 328
cars found: 20
opening page 329
cars found: 20
opening page 330
cars found: 20
opening page 331
cars found: 20
opening page 332
cars found: 20

In [45]:
df_new_delhi = pd.DataFrame(all_cars)
print("Total new-delhi cars:", len(df_new_delhi))
df_new_delhi.head()

Total new-delhi cars: 6640

,car_brand,car_name,year,km_driven,fuel,transmission,price,city
0,BMW,BMW X5xDrive 30d xLine,2022,"44,266kms",Diesel,Automatic,₹64 Lakh,new-delhi
1,Toyota,Toyota VellfireHi,2025,"5,900kms",Petrol,Automatic,₹1.19 Crore,new-delhi
2,Mercedes-Benz,Mercedes-Benz E-ClassExclusive E 200 BSIV,2019,"70,000kms",Petrol,Automatic,₹31.49 Lakh,new-delhi
3,Mercedes-Benz,Mercedes-Benz E-ClassExpression E 200 BSIV,2019,"28,000kms",Petrol,Automatic,₹37.50 Lakh,new-delhi
4,Mercedes-Benz,Mercedes-Benz E-ClassExpression E 200 BSIV,2019,"14,100kms",Petrol,Automatic,₹34.75 Lakh,new-delhi

In [46]:
df_new_delhi.to_csv(r"C:\Users\admin\Desktop\Used_Cars_ Price_Analysis\data\raw\used_cars_new-delhi_raw.csv", index=False)
print("Saved: used_cars_new-delhi_raw.csv")

Saved: used_cars_new-delhi_raw.csv

# Noida

In [47]:
all_cars = []
page = 1
max_pages = 125

while page <= max_pages:
    print(f"opening page {page}")

    if page == 1:
        url = "https://www.cardekho.com/used-cars+in+noida"
    else:
        url = f"https://www.cardekho.com/used-cars+in+noida/page-{page}"

    driver.get(url)
    time.sleep(5)

    soup = BeautifulSoup(driver.page_source, "html.parser")
    cards = soup.find_all("div",class_="NewUcExCard")

    print("cars found:",len(cards))

    for card in cards:
        try:
            #--Title--
            title = card.find("h3",class_="title").get_text(strip=True)

            

            #--year--
            year = None
            for y in range(1990, 2027):
                if str(y) in title:
                    year = str(y)
                    title = title.replace(str(y), str(y) + " ")

                    break
                    
            #--car name--
            car_name = title.strip()
            if year:
                car_name = car_name.replace(year, "").strip()

            #--Brand--
            car_brand =  None
            for b in brands:
                if b in title:
                    car_brand = b
                    break

            #--Details--
            details = card.find("div", class_="dotsDetails")
            if details:
                parts = [x.strip() for x in details.get_text(strip=True).split("•")]
                km_driven = parts[0] if len(parts) > 0 else None
                fuel = parts[1] if len(parts) > 1 else None
                transmission = parts[2] if len(parts) > 2 else None
            else:
                km_driven = fuel = transmission = None


            #--price--
            price_tag = card.find("div", class_="priceAssured")
            price = price_tag.get_text(strip=True) if price_tag else None
            
            #---Append---
            all_cars.append({
            "car_brand": car_brand,
            "car_name":car_name,
            "year":year,
            "km_driven":km_driven,
            "fuel":fuel,
            "transmission":transmission,
            "price":price,
            "city":"noida"
            })

        except Exception:
            continue

    page += 1

opening page 1
cars found: 20
opening page 2
cars found: 20
opening page 3
cars found: 20
opening page 4
cars found: 20
opening page 5
cars found: 20
opening page 6
cars found: 20
opening page 7
cars found: 20
opening page 8
cars found: 20
opening page 9
cars found: 20
opening page 10
cars found: 20
opening page 11
cars found: 20
opening page 12
cars found: 20
opening page 13
cars found: 20
opening page 14
cars found: 20
opening page 15
cars found: 20
opening page 16
cars found: 20
opening page 17
cars found: 20
opening page 18
cars found: 20
opening page 19
cars found: 20
opening page 20
cars found: 20
opening page 21
cars found: 20
opening page 22
cars found: 20
opening page 23
cars found: 20
opening page 24
cars found: 20
opening page 25
cars found: 20
opening page 26
cars found: 20
opening page 27
cars found: 20
opening page 28
cars found: 20
opening page 29
cars found: 20
opening page 30
cars found: 20
opening page 31
cars found: 20
opening page 32
cars found: 20
opening page 33
cars found: 20
opening page 34
cars found: 20
opening page 35
cars found: 20
opening page 36
cars found: 20
opening page 37
cars found: 20
opening page 38
cars found: 20
opening page 39
cars found: 20
opening page 40
cars found: 20
opening page 41
cars found: 20
opening page 42
cars found: 20
opening page 43
cars found: 20
opening page 44
cars found: 20
opening page 45
cars found: 20
opening page 46
cars found: 20
opening page 47
cars found: 20
opening page 48
cars found: 20
opening page 49
cars found: 20
opening page 50
cars found: 20
opening page 51
cars found: 20
opening page 52
cars found: 20
opening page 53
cars found: 20
opening page 54
cars found: 20
opening page 55
cars found: 20
opening page 56
cars found: 20
opening page 57
cars found: 20
opening page 58
cars found: 20
opening page 59
cars found: 20
opening page 60
cars found: 20
opening page 61
cars found: 20
opening page 62
cars found: 20
opening page 63
cars found: 20
opening page 64
cars found: 20
opening page 65
cars found: 20
opening page 66
cars found: 20
opening page 67
cars found: 20
opening page 68
cars found: 20
opening page 69
cars found: 20
opening page 70
cars found: 20
opening page 71
cars found: 20
opening page 72
cars found: 20
opening page 73
cars found: 20
opening page 74
cars found: 20
opening page 75
cars found: 20
opening page 76
cars found: 20
opening page 77
cars found: 20
opening page 78
cars found: 20
opening page 79
cars found: 20
opening page 80
cars found: 20
opening page 81
cars found: 20
opening page 82
cars found: 20
opening page 83
cars found: 20
opening page 84
cars found: 20
opening page 85
cars found: 20
opening page 86
cars found: 20
opening page 87
cars found: 20
opening page 88
cars found: 20
opening page 89
cars found: 20
opening page 90
cars found: 20
opening page 91
cars found: 20
opening page 92
cars found: 20
opening page 93
cars found: 20
opening page 94
cars found: 20
opening page 95
cars found: 20
opening page 96
cars found: 20
opening page 97
cars found: 20
opening page 98
cars found: 20
opening page 99
cars found: 20
opening page 100
cars found: 20
opening page 101
cars found: 20
opening page 102
cars found: 20
opening page 103
cars found: 20
opening page 104
cars found: 20
opening page 105
cars found: 20
opening page 106
cars found: 20
opening page 107
cars found: 20
opening page 108
cars found: 20
opening page 109
cars found: 20
opening page 110
cars found: 20
opening page 111
cars found: 20
opening page 112
cars found: 20
opening page 113
cars found: 20
opening page 114
cars found: 20
opening page 115
cars found: 20
opening page 116
cars found: 20
opening page 117
cars found: 20
opening page 118
cars found: 20
opening page 119
cars found: 20
opening page 120
cars found: 20
opening page 121
cars found: 20
opening page 122
cars found: 20
opening page 123
cars found: 20
opening page 124
cars found: 20
opening page 125
cars found: 20

In [48]:
df_noida = pd.DataFrame(all_cars)
print("Total noida cars:", len(df_noida))
df_noida.head()

Total noida cars: 2500

,car_brand,car_name,year,km_driven,fuel,transmission,price,city
0,Mercedes-Benz,Mercedes-Benz EQE SUV500 4MATIC,2023,"19,000kms",Electric,Automatic,₹85 Lakh,noida
1,Toyota,Toyota Innova HycrossZX Hybrid,2024,"40,000kms",Petrol,Automatic,₹30.70 Lakh,noida
2,Maruti,Maruti BalenoAlpha Diesel,2016,"94,777kms",Diesel,Manual,₹4.19 Lakh,noida
3,Maruti,Maruti BalenoDelta Diesel,2017,"38,504kms",Diesel,Manual,₹4.41 Lakh,noida
4,Maruti,Maruti BalenoZeta Diesel,2016,"71,115kms",Diesel,Manual,₹4.09 Lakh,noida

In [49]:
df_noida.to_csv(r"C:\Users\admin\Desktop\Used_Cars_ Price_Analysis\data\raw\used_cars_noida_raw.csv", index=False)
print("Saved: used_cars_noida_raw.csv")

Saved: used_cars_noida_raw.csv

# Kolkata

In [50]:
all_cars = []
page = 1
max_pages = 66

while page <= max_pages:
    print(f"opening page {page}")

    if page == 1:
        url = "https://www.cardekho.com/used-cars+in+kolkata"
    else:
        url = f"https://www.cardekho.com/used-cars+in+kolkata/page-{page}"

    driver.get(url)
    time.sleep(5)

    soup = BeautifulSoup(driver.page_source, "html.parser")
    cards = soup.find_all("div",class_="NewUcExCard")

    print("cars found:",len(cards))

    for card in cards:
        try:
            #--Title--
            title = card.find("h3",class_="title").get_text(strip=True)

             

            #--year--
            year = None
            for y in range(1990, 2027):
                if str(y) in title:
                    year = str(y)
                    title = title.replace(str(y), str(y) + " ")

                    break

            #--car name--
            car_name = title.strip()
            if year:
                car_name = car_name.replace(year, "").strip()

            #--Brand--
            car_brand =  None
            for b in brands:
                if b in title:
                    car_brand = b
                    break

            #--Details--
            details = card.find("div", class_="dotsDetails")
            if details:
                parts = [x.strip() for x in details.get_text(strip=True).split("•")]
                km_driven = parts[0] if len(parts) > 0 else None
                fuel = parts[1] if len(parts) > 1 else None
                transmission = parts[2] if len(parts) > 2 else None
            else:
                km_driven = fuel = transmission = None


            #--price--
            price_tag = card.find("div", class_="priceAssured")
            price = price_tag.get_text(strip=True) if price_tag else None
            
            #---Append---
            all_cars.append({
            "car_brand": car_brand,
            "car_name":car_name,
            "year":year,
            "km_driven":km_driven,
            "fuel":fuel,
            "transmission":transmission,
            "price":price,
            "city":"kolkata"
            })

        except Exception:
            continue

    page += 1

opening page 1
cars found: 20
opening page 2
cars found: 20
opening page 3
cars found: 20
opening page 4
cars found: 20
opening page 5
cars found: 20
opening page 6
cars found: 20
opening page 7
cars found: 20
opening page 8
cars found: 20
opening page 9
cars found: 20
opening page 10
cars found: 20
opening page 11
cars found: 20
opening page 12
cars found: 20
opening page 13
cars found: 20
opening page 14
cars found: 20
opening page 15
cars found: 20
opening page 16
cars found: 20
opening page 17
cars found: 20
opening page 18
cars found: 20
opening page 19
cars found: 20
opening page 20
cars found: 20
opening page 21
cars found: 20
opening page 22
cars found: 20
opening page 23
cars found: 20
opening page 24
cars found: 20
opening page 25
cars found: 20
opening page 26
cars found: 20
opening page 27
cars found: 20
opening page 28
cars found: 20
opening page 29
cars found: 20
opening page 30
cars found: 20
opening page 31
cars found: 20
opening page 32
cars found: 20
opening page 33
cars found: 20
opening page 34
cars found: 20
opening page 35
cars found: 20
opening page 36
cars found: 20
opening page 37
cars found: 20
opening page 38
cars found: 20
opening page 39
cars found: 20
opening page 40
cars found: 20
opening page 41
cars found: 20
opening page 42
cars found: 20
opening page 43
cars found: 20
opening page 44
cars found: 20
opening page 45
cars found: 20
opening page 46
cars found: 20
opening page 47
cars found: 20
opening page 48
cars found: 20
opening page 49
cars found: 20
opening page 50
cars found: 20
opening page 51
cars found: 20
opening page 52
cars found: 20
opening page 53
cars found: 20
opening page 54
cars found: 20
opening page 55
cars found: 20
opening page 56
cars found: 20
opening page 57
cars found: 20
opening page 58
cars found: 20
opening page 59
cars found: 20
opening page 60
cars found: 20
opening page 61
cars found: 20
opening page 62
cars found: 20
opening page 63
cars found: 20
opening page 64
cars found: 20
opening page 65
cars found: 20
opening page 66
cars found: 20

In [51]:
df_kolkata = pd.DataFrame(all_cars)
print("Total kolkata cars:", len(df_kolkata))
df_kolkata.head()

Total kolkata cars: 1320

,car_brand,car_name,year,km_driven,fuel,transmission,price,city
0,Lamborghini,Lamborghini UrusV8,2020,"19,500kms",Petrol,Automatic,₹3.15 Crore,kolkata
1,Maruti,Maruti BalenoZeta,2021,"51,000kms",Petrol,Manual,₹4.75 Lakh,kolkata
2,Hyundai,Hyundai Grand i10 NiosCorp Edition,2022,"31,000kms",Petrol,Manual,₹4.69 Lakh,kolkata
3,Honda,Honda City1.5 V MT Sunroof,2012,"69,000kms",Petrol,Manual,₹2.25 Lakh,kolkata
4,Tata,Tata Tigor EVXZ Plus,2022,"20,000kms",Electric,Automatic,₹7.50 Lakh,kolkata

In [52]:
df_kolkata.to_csv(r"C:\Users\admin\Desktop\Used_Cars_ Price_Analysis\data\raw\used_cars_kolkata_raw.csv", index=False)
print("Saved: used_cars_kolkata_raw.csv")

Saved: used_cars_kolkata_raw.csv